/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 14, 2017 at 5:17:22 PM Greenwich Mean Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CNContactPickerDelegate <NSObject>
@optional
-(void)contactPickerDidCancel:(id)arg1;
-(void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContactProperty:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContacts:(id)arg2;
-(void)contactPicker:(id)arg1 didSelectContactProperties:(id)arg2;

@end

