/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 14, 2017 at 5:17:20 PM Greenwich Mean Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PKPassFaceDelegate <NSObject>
@required
-(BOOL)passFaceBarcodeButtonEnabled;
-(void)passFaceFlipButtonPressed:(id)arg1;
-(void)passFaceBarcodeButtonPressed:(id)arg1;
-(void)passBackFaceShareButtonPressed:(id)arg1;
-(void)passFaceDeleteButtonPressed:(id)arg1;
-(BOOL)passFaceDeleteButtonEnabled;

@end

