/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 14, 2017 at 5:17:21 PM Greenwich Mean Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PassKitUI/PassKitUI-Structs.h>
#import <UIKit/UIPresentationController.h>

@class UIView, NSLayoutConstraint, NSHashTable;

@interface PKPaymentAuthorizationPresentationController : UIPresentationController {

	UIView* _dimmingView;
	NSLayoutConstraint* _topConstraint;
	NSLayoutConstraint* _leftConstraint;
	NSLayoutConstraint* _rightConstraint;
	CGSize _preferredContentSize;
	NSHashTable* _observers;

}

@property (nonatomic,readonly) CGSize maximumContentSize; 
@property (nonatomic,readonly) CGSize contentSize; 
-(CGSize)contentSize;
-(void)dealloc;
-(BOOL)shouldRemovePresentersView;
-(void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1 ;
-(void)presentationTransitionWillBegin;
-(void)dismissalTransitionWillBegin;
-(void)containerViewWillLayoutSubviews;
-(id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2 ;
-(CGSize)maximumContentSize;
-(void)_notifyObserversAboutWillAdjustToSize:(CGSize)arg1 ;
-(void)_notifyObserversAboutDidAdjustToSize:(CGSize)arg1 ;
-(void)addPresentationObserver:(id)arg1 ;
-(void)removePresentationObserver:(id)arg1 ;
@end

