/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 14, 2017 at 5:17:20 PM Greenwich Mean Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <PassKitUI/PassKitUI-Structs.h>
#import <PassKitUI/PKPaymentSetupInfoView.h>

@class UIView;

@interface PKPaymentSetupWalletInfoView : PKPaymentSetupInfoView {

	UIView* _separator;

}
-(void)layoutSubviews;
-(void)_createSubviews;
-(id)initWithFrame:(CGRect)arg1 context:(long long)arg2 heroImageController:(id)arg3 hasSupportingHardware:(BOOL)arg4 region:(id)arg5 ;
@end

