/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:54:49 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NTKCompanionAppLibraryObserver <NSObject>
@optional
-(void)appLibrary:(id)arg1 didAddApp:(id)arg2;
-(void)appLibrary:(id)arg1 didUpdateApp:(id)arg2;
-(void)appLibrary:(id)arg1 didRemoveApp:(id)arg2;
-(void)appLibrary:(id)arg1 didUpdateAppIcon:(id)arg2;

@end

