/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:54:47 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NTKSafeLocketReaderDelegate;
@class NSString, NPTOLocket;

@interface NTKSafeLocketReader : NSObject {

	NSString* _defaultPhotoPath;
	BOOL _isPhotoLibraryAvailable;
	NPTOLocket* _locket;
	id<NTKSafeLocketReaderDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<NTKSafeLocketReaderDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) BOOL firstUnlockHasOccurred; 
@property (nonatomic,readonly) unsigned long long numberOfLoadedPhotos; 
@property (nonatomic,readonly) unsigned long long numberOfTotalPhotos; 
-(void)setDelegate:(id<NTKSafeLocketReaderDelegate>)arg1 ;
-(id<NTKSafeLocketReaderDelegate>)delegate;
-(unsigned long long)numberOfLoadedPhotos;
-(unsigned long long)numberOfTotalPhotos;
-(void)loadPhotoAtIndex:(unsigned long long)arg1 handler:(/*^block*/id)arg2 ;
-(unsigned long long)indexOfPhotoWithIdentifier:(id)arg1 ;
-(id)initWithDefaultPhotoPath:(id)arg1 ;
-(BOOL)firstUnlockHasOccurred;
@end

