/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:55:47 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/NanoMailKitServer.framework/NanoMailKitServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol NNMKMailboxItem <NSObject>
@property (nonatomic,retain) NSString * subject; 
@property (nonatomic,retain) NSString * preview; 
@property (assign,nonatomic) unsigned long long status; 
@required
-(NSString *)subject;
-(void)setSubject:(id)arg1;
-(unsigned long long)status;
-(void)setStatus:(unsigned long long)arg1;
-(NSString *)preview;
-(void)setPreview:(id)arg1;
-(BOOL)checkState:(unsigned long long)arg1;
-(void)addState:(unsigned long long)arg1;
-(void)removeState:(unsigned long long)arg1;

@end

