/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSAppleIDAuthControllerDelegate.h>

@protocol COSAppleIDSilentSignInControllerDelegate;
@class NRDevice, ACAccountStore, ACAccount, COSAppleIDAuthController;

@interface COSAppleIDSilentSignInController : NSObject <COSAppleIDAuthControllerDelegate> {

	BOOL _shouldSigniMessageAccountSeparately;
	BOOL _shouldSignFaceTimeAccountSeparately;
	BOOL _faceTimeAccountIsForSameUserAsiCloudAccount;
	BOOL _faceTimeAccountIsForSameUserAsiMessageAccount;
	id<COSAppleIDSilentSignInControllerDelegate> _delegate;
	NRDevice* _device;
	ACAccountStore* _accountStore;
	ACAccount* _iCloudAccount;
	ACAccount* _iMessageAccount;
	ACAccount* _faceTimeAccount;
	COSAppleIDAuthController* _iCloudAuthController;
	COSAppleIDAuthController* _iMessageAuthController;
	COSAppleIDAuthController* _faceTimeAuthController;

}

@property (nonatomic,retain) NRDevice * device;                                                         //@synthesize device=_device - In the implementation block
@property (nonatomic,retain) ACAccountStore * accountStore;                                             //@synthesize accountStore=_accountStore - In the implementation block
@property (nonatomic,retain) ACAccount * iCloudAccount;                                                 //@synthesize iCloudAccount=_iCloudAccount - In the implementation block
@property (nonatomic,retain) ACAccount * iMessageAccount;                                               //@synthesize iMessageAccount=_iMessageAccount - In the implementation block
@property (nonatomic,retain) ACAccount * faceTimeAccount;                                               //@synthesize faceTimeAccount=_faceTimeAccount - In the implementation block
@property (nonatomic,retain) COSAppleIDAuthController * iCloudAuthController;                           //@synthesize iCloudAuthController=_iCloudAuthController - In the implementation block
@property (nonatomic,retain) COSAppleIDAuthController * iMessageAuthController;                         //@synthesize iMessageAuthController=_iMessageAuthController - In the implementation block
@property (nonatomic,retain) COSAppleIDAuthController * faceTimeAuthController;                         //@synthesize faceTimeAuthController=_faceTimeAuthController - In the implementation block
@property (assign,nonatomic) BOOL shouldSigniMessageAccountSeparately;                                  //@synthesize shouldSigniMessageAccountSeparately=_shouldSigniMessageAccountSeparately - In the implementation block
@property (assign,nonatomic) BOOL shouldSignFaceTimeAccountSeparately;                                  //@synthesize shouldSignFaceTimeAccountSeparately=_shouldSignFaceTimeAccountSeparately - In the implementation block
@property (assign,nonatomic) BOOL faceTimeAccountIsForSameUserAsiCloudAccount;                          //@synthesize faceTimeAccountIsForSameUserAsiCloudAccount=_faceTimeAccountIsForSameUserAsiCloudAccount - In the implementation block
@property (assign,nonatomic) BOOL faceTimeAccountIsForSameUserAsiMessageAccount;                        //@synthesize faceTimeAccountIsForSameUserAsiMessageAccount=_faceTimeAccountIsForSameUserAsiMessageAccount - In the implementation block
@property (assign,nonatomic,__weak) id<COSAppleIDSilentSignInControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(double)silentAuthTimeout;
+(id)idsAccount;
-(void)appleIDAuthController:(id)arg1 didSignInWithSuccess:(BOOL)arg2 error:(id)arg3 ;
-(void)setICloudAccount:(ACAccount *)arg1 ;
-(ACAccount *)iMessageAccount;
-(void)setIMessageAccount:(ACAccount *)arg1 ;
-(ACAccount *)faceTimeAccount;
-(void)setFaceTimeAccount:(ACAccount *)arg1 ;
-(id)initWithDelegate:(id)arg1 device:(id)arg2 ;
-(void)startSigninIn;
-(COSAppleIDAuthController *)iCloudAuthController;
-(void)setICloudAuthController:(COSAppleIDAuthController *)arg1 ;
-(COSAppleIDAuthController *)iMessageAuthController;
-(void)setIMessageAuthController:(COSAppleIDAuthController *)arg1 ;
-(COSAppleIDAuthController *)faceTimeAuthController;
-(void)setFaceTimeAuthController:(COSAppleIDAuthController *)arg1 ;
-(BOOL)shouldSigniMessageAccountSeparately;
-(void)setShouldSigniMessageAccountSeparately:(BOOL)arg1 ;
-(BOOL)shouldSignFaceTimeAccountSeparately;
-(void)setShouldSignFaceTimeAccountSeparately:(BOOL)arg1 ;
-(BOOL)faceTimeAccountIsForSameUserAsiCloudAccount;
-(void)setFaceTimeAccountIsForSameUserAsiCloudAccount:(BOOL)arg1 ;
-(BOOL)faceTimeAccountIsForSameUserAsiMessageAccount;
-(void)setFaceTimeAccountIsForSameUserAsiMessageAccount:(BOOL)arg1 ;
-(void)setDelegate:(id<COSAppleIDSilentSignInControllerDelegate>)arg1 ;
-(id<COSAppleIDSilentSignInControllerDelegate>)delegate;
-(void)setAccountStore:(ACAccountStore *)arg1 ;
-(ACAccountStore *)accountStore;
-(NRDevice *)device;
-(void)setDevice:(NRDevice *)arg1 ;
-(ACAccount *)iCloudAccount;
@end

