/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol COSAppInstallationDelegate <NSObject>
@required
-(void)didCompleteInstallationWithSuccess:(BOOL)arg1;
-(void)didInitiatePurchase;
-(void)didBeginInstallationWithSuccess:(BOOL)arg1;
-(void)appIsAvailableStateDidChange:(unsigned long long)arg1;

@end

