/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <AppleAccount/AAGenericTermsUIRequest.h>

@class NRDevice, NSURLRequest;

@interface COSAAGenericTermsUIRequest : AAGenericTermsUIRequest {

	BOOL _showWarranty;
	NRDevice* _device;

}

@property (nonatomic,retain) NRDevice * device;              //@synthesize device=_device - In the implementation block
@property (assign,nonatomic) BOOL showWarranty;              //@synthesize showWarranty=_showWarranty - In the implementation block
@property (readonly) NSURLRequest * urlRequest; 
+(id)clientInfoHeaderForDevice:(id)arg1 ;
+(id)pairedClientInfoHeaderName;
+(id)deviceModelHeaderName;
-(id)initWithGizmoDevice:(id)arg1 showWarranty:(BOOL)arg2 ;
-(BOOL)showWarranty;
-(void)setShowWarranty:(BOOL)arg1 ;
-(NSURLRequest *)urlRequest;
-(NRDevice *)device;
-(void)setDevice:(NRDevice *)arg1 ;
@end

