/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Preferences/PSSpecifierDataSource.h>

@class NSSManager, NRDevice, NSNumber;

@interface COSAboutDataSource : PSSpecifierDataSource {

	BOOL _hasStartedFetchingAboutInfo;
	BOOL _hasFetchedAboutInfo;
	BOOL _errorOccurredFetchingAboutInfo;
	BOOL _displayNetworkProgressIndicator;
	BOOL _showRegulatoryModelNumber;
	NSSManager* _nssManager;
	NRDevice* _device;
	NSNumber* _numberOfApps;
	NSNumber* _numberOfSongs;
	NSNumber* _numberOfPhotos;
	unsigned long long _storageAvailable;

}

@property (nonatomic,retain) NSSManager * nssManager;                           //@synthesize nssManager=_nssManager - In the implementation block
@property (nonatomic,retain) NRDevice * device;                                 //@synthesize device=_device - In the implementation block
@property (assign,nonatomic) BOOL hasStartedFetchingAboutInfo;                  //@synthesize hasStartedFetchingAboutInfo=_hasStartedFetchingAboutInfo - In the implementation block
@property (assign,nonatomic) BOOL hasFetchedAboutInfo;                          //@synthesize hasFetchedAboutInfo=_hasFetchedAboutInfo - In the implementation block
@property (assign,nonatomic) BOOL errorOccurredFetchingAboutInfo;               //@synthesize errorOccurredFetchingAboutInfo=_errorOccurredFetchingAboutInfo - In the implementation block
@property (assign,nonatomic) BOOL displayNetworkProgressIndicator;              //@synthesize displayNetworkProgressIndicator=_displayNetworkProgressIndicator - In the implementation block
@property (nonatomic,retain) NSNumber * numberOfApps;                           //@synthesize numberOfApps=_numberOfApps - In the implementation block
@property (nonatomic,retain) NSNumber * numberOfSongs;                          //@synthesize numberOfSongs=_numberOfSongs - In the implementation block
@property (nonatomic,retain) NSNumber * numberOfPhotos;                         //@synthesize numberOfPhotos=_numberOfPhotos - In the implementation block
@property (assign,nonatomic) unsigned long long storageAvailable;               //@synthesize storageAvailable=_storageAvailable - In the implementation block
@property (assign,nonatomic) BOOL showRegulatoryModelNumber;                    //@synthesize showRegulatoryModelNumber=_showRegulatoryModelNumber - In the implementation block
-(void)displayNetworkActivityIndicator:(BOOL)arg1 ;
-(void)queryPairedDevice;
-(void)handleAboutInfo:(id)arg1 error:(id)arg2 ;
-(void)hideNetworkActivityIndicatorOnceRemoteQueriesHaveCompleted;
-(id)guardedUint64StringValue:(unsigned long long)arg1 ;
-(id)getNumberOfSongs:(id)arg1 ;
-(id)getNumberOfPhotos:(id)arg1 ;
-(id)getNumberOfApps:(id)arg1 ;
-(id)getStorageAvailable:(id)arg1 ;
-(id)getStorageCapacity:(id)arg1 ;
-(id)getSystemVersion:(id)arg1 ;
-(id)getDeviceModel:(id)arg1 ;
-(void)updateModelSpecifier:(id)arg1 ;
-(id)getWiFiAddress:(id)arg1 ;
-(id)getBTAddress:(id)arg1 ;
-(void)tappedAppleLegalLink;
-(void)showUserManual:(id)arg1 ;
-(BOOL)hasStartedFetchingAboutInfo;
-(void)setHasStartedFetchingAboutInfo:(BOOL)arg1 ;
-(BOOL)hasFetchedAboutInfo;
-(void)setHasFetchedAboutInfo:(BOOL)arg1 ;
-(BOOL)errorOccurredFetchingAboutInfo;
-(void)setErrorOccurredFetchingAboutInfo:(BOOL)arg1 ;
-(BOOL)displayNetworkProgressIndicator;
-(void)setDisplayNetworkProgressIndicator:(BOOL)arg1 ;
-(NSNumber *)numberOfApps;
-(void)setNumberOfApps:(NSNumber *)arg1 ;
-(NSNumber *)numberOfSongs;
-(void)setNumberOfSongs:(NSNumber *)arg1 ;
-(unsigned long long)storageAvailable;
-(void)setStorageAvailable:(unsigned long long)arg1 ;
-(BOOL)showRegulatoryModelNumber;
-(void)setShowRegulatoryModelNumber:(BOOL)arg1 ;
-(id)init;
-(void)dealloc;
-(id)specifiersForSpecifier:(id)arg1 observer:(id)arg2 ;
-(void)loadSpecifiers;
-(NSNumber *)numberOfPhotos;
-(void)setNumberOfPhotos:(NSNumber *)arg1 ;
-(id)getSerialNumber:(id)arg1 ;
-(void)setDeviceName:(id)arg1 specifier:(id)arg2 ;
-(id)getDeviceName:(id)arg1 ;
-(NSSManager *)nssManager;
-(void)setNssManager:(NSSManager *)arg1 ;
-(NRDevice *)device;
-(void)setDevice:(NRDevice *)arg1 ;
-(id)dash;
@end

