/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class COSGetStartedView;

@interface COSGetStartedInternalViewController : UIViewController {

	BOOL _wantsToAnimate;
	COSGetStartedView* _getStartedView;

}

@property (nonatomic,retain) COSGetStartedView * getStartedView;              //@synthesize getStartedView=_getStartedView - In the implementation block
@property (assign,nonatomic) BOOL wantsToAnimate;                             //@synthesize wantsToAnimate=_wantsToAnimate - In the implementation block
-(COSGetStartedView *)getStartedView;
-(void)setGetStartedView:(COSGetStartedView *)arg1 ;
-(BOOL)wantsToAnimate;
-(void)setWantsToAnimate:(BOOL)arg1 ;
-(id)init;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)_stopAnimating;
-(void)_startAnimating;
@end

