/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSSetupPageViewController.h>

@class COSHealthStatsTableViewController;

@interface COSHealthStatsViewController : COSSetupPageViewController {

	COSHealthStatsTableViewController* _tableViewController;

}

@property (nonatomic,retain) COSHealthStatsTableViewController * tableViewController;              //@synthesize tableViewController=_tableViewController - In the implementation block
-(void)tappedContinue:(id)arg1 ;
-(id)viewController;
-(void)setTableViewController:(COSHealthStatsTableViewController *)arg1 ;
-(COSHealthStatsTableViewController *)tableViewController;
@end

