/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/Bridge-Structs.h>
#import <UIKit/UIView.h>

@protocol OS_dispatch_queue, COSMagicCodeScannerDelegate;
@class AVCaptureSession, AVCaptureDevice, AVCaptureVideoPreviewLayer, NSObject, UITapGestureRecognizer, CALayer;

@interface COSMagicCodeScanner : UIView {

	AVCaptureSession* _session;
	AVCaptureDevice* _device;
	AVCaptureVideoPreviewLayer* _previewLayer;
	NSObject*<OS_dispatch_queue> _queue;
	HCImagePerspectiveReader* _reader;
	unsigned long long _readerUVWidth;
	unsigned long long _readerUVHeight;
	unsigned long long _readerUVBytesPerRow;
	double _watermark;
	CFArrayRef _pixelBufferPyramidArray;
	OpaqueVTPixelTransferSessionRef _pixelTransferSession;
	double _lastWmTime;
	double _lastFrameTime;
	double _lastPayloadTime;
	double _nextFrameTime;
	float _lastWmProgress;
	unsigned _missWmCount;
	BOOL _canUseCamera;
	BOOL _isScanningForCode;
	id<COSMagicCodeScannerDelegate> _delegate;
	UITapGestureRecognizer* _debugUIRecognizer;
	CALayer* _progressBGLayer;
	CALayer* _progressLayer;

}

@property (nonatomic,retain) UITapGestureRecognizer * debugUIRecognizer;                   //@synthesize debugUIRecognizer=_debugUIRecognizer - In the implementation block
@property (nonatomic,retain) CALayer * progressBGLayer;                                    //@synthesize progressBGLayer=_progressBGLayer - In the implementation block
@property (nonatomic,retain) CALayer * progressLayer;                                      //@synthesize progressLayer=_progressLayer - In the implementation block
@property (assign,nonatomic,__weak) id<COSMagicCodeScannerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) BOOL canUseCamera;                                          //@synthesize canUseCamera=_canUseCamera - In the implementation block
@property (assign,nonatomic) BOOL isScanningForCode;                                       //@synthesize isScanningForCode=_isScanningForCode - In the implementation block
-(void)toggleDebugUI:(id)arg1 ;
-(void)setCameraAttributes;
-(BOOL)isScanningForCode;
-(void)setIsScanningForCode:(BOOL)arg1 ;
-(UITapGestureRecognizer *)debugUIRecognizer;
-(void)setDebugUIRecognizer:(UITapGestureRecognizer *)arg1 ;
-(CALayer *)progressBGLayer;
-(void)setProgressBGLayer:(CALayer *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<COSMagicCodeScannerDelegate>)arg1 ;
-(void)dealloc;
-(id<COSMagicCodeScannerDelegate>)delegate;
-(void)stopRunning;
-(void)handleRuntimeError:(id)arg1 ;
-(BOOL)canUseCamera;
-(void)startRunning;
-(void)captureOutput:(id)arg1 didOutputSampleBuffer:(opaqueCMSampleBufferRef)arg2 fromConnection:(id)arg3 ;
-(CALayer *)progressLayer;
-(void)setProgressLayer:(CALayer *)arg1 ;
-(void)_changeCameraConfiguration;
-(id)setupCameraSession;
@end

