/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BridgePreferences/BPSNotificationAppController.h>

@class BBSectionInfo;

@interface COSNotificationAppController : BPSNotificationAppController {

	BBSectionInfo* _bbSectionInfo;

}

@property (nonatomic,retain) BBSectionInfo * bbSectionInfo;              //@synthesize bbSectionInfo=_bbSectionInfo - In the implementation block
-(BBSectionInfo *)bbSectionInfo;
-(id)localizedPaneTitle;
-(void)setBbSectionInfo:(BBSectionInfo *)arg1 ;
-(id)applicationBundleIdentifier;
@end

