/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/Bridge-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, NSString;

@interface COSPinKeyView : UIView {

	NSArray* _dashLayers;
	NSArray* _digitLayers;
	NSString* _digits;

}

@property (nonatomic,retain) NSArray * dashLayers;               //@synthesize dashLayers=_dashLayers - In the implementation block
@property (nonatomic,retain) NSArray * digitLayers;              //@synthesize digitLayers=_digitLayers - In the implementation block
@property (nonatomic,copy) NSString * digits;                    //@synthesize digits=_digits - In the implementation block
-(long long)expectedPinLength;
-(void)setCodeLength:(long long)arg1 ;
-(NSArray *)dashLayers;
-(void)setDashLayers:(NSArray *)arg1 ;
-(NSArray *)digitLayers;
-(void)setDigitLayers:(NSArray *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDigits:(NSString *)arg1 ;
-(NSString *)digits;
@end

