/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Preferences/PSSoftwareUpdateAnimatedIcon.h>

@class NSString;

@interface COSSoftwareUpdateAnimatedIcon : PSSoftwareUpdateAnimatedIcon {

	NSString* _outerGearImageName;

}

@property (nonatomic,retain) NSString * outerGearImageName;              //@synthesize outerGearImageName=_outerGearImageName - In the implementation block
-(NSString *)outerGearImageName;
-(void)setOuterGearImageName:(NSString *)arg1 ;
-(id)innerGearView;
-(id)outerGearShadowView;
-(id)outerGearView;
@end

