/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Bridge/COSWatchView.h>

@class UIImageView;

@interface COSSetupDeviceSyncView : COSWatchView {

	UIImageView* _watchImageView;

}

@property (nonatomic,readonly) UIImageView * watchImageView;              //@synthesize watchImageView=_watchImageView - In the implementation block
-(UIImageView *)watchImageView;
@end

