/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NACVolumeControllerDelegate <NSObject>
@optional
-(void)volumeControllerDidUpdateMutedState:(id)arg1;
-(void)volumeControllerDidUpdateEUVolumeLimit:(id)arg1;
-(void)volumeControllerDidUpdateVolumeWarningEnabled:(id)arg1;
-(void)volumeControllerDidUpdateHapticIntensity:(id)arg1;
-(void)volumeControllerDidUpdateSystemMutedState:(id)arg1;
-(void)volumeControllerDidUpdateProminentHapticState:(id)arg1;

@required
-(void)volumeControllerDidUpdateVolumeControlAvailibility:(id)arg1;
-(void)volumeControllerDidUpdateVolumeValue:(id)arg1;

@end

