/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:48:11 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Bridge.app/Bridge
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PSYProgressObserverDelegate <NSObject>
@required
-(void)progressObserverDidChangeState:(id)arg1;
-(void)progressObserverDidChangeProgress:(id)arg1;
-(void)progressObserver:(id)arg1 didFinishActivity:(id)arg2 withError:(id)arg3;

@end

