/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface AEAssetEngine : NSObject
+(id)cachePathForAssetType:(id)arg1 withAssetID:(id)arg2 ;
+(void)setAppInfoMgr:(id)arg1 ;
+(id)appInfoMgr;
+(void)setStoreMgr:(id)arg1 ;
+(id)storeMgr;
+(void)setProofingMgr:(id)arg1 ;
+(id)proofingMgr;
+(void)setLibraryMgr:(id)arg1 ;
+(id)libraryMgr;
+(id)cachePathForAssetID:(id)arg1 ;
@end

