/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class NSString;

@interface BKSProcessAssertion_IM : NSObject {

	unsigned _flags;
	unsigned _reason;
	NSString* _name;
	/*^block*/id _invalidationHandler;
	SBSProcessAssertionRef _sbsProcessAssertion;

}

@property (assign) SBSProcessAssertionRef sbsProcessAssertion;              //@synthesize sbsProcessAssertion=_sbsProcessAssertion - In the implementation block
@property (nonatomic,readonly) NSString * name;                             //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) BOOL valid; 
@property (nonatomic,readonly) unsigned flags;                              //@synthesize flags=_flags - In the implementation block
@property (nonatomic,readonly) unsigned reason;                             //@synthesize reason=_reason - In the implementation block
@property (copy) id invalidationHandler;                                    //@synthesize invalidationHandler=_invalidationHandler - In the implementation block
+(id)NameForReason:(unsigned)arg1 ;
-(void)setSbsProcessAssertion:(SBSProcessAssertionRef)arg1 ;
-(SBSProcessAssertionRef)sbsProcessAssertion;
-(void)dealloc;
-(NSString *)name;
-(void)invalidate;
-(id)initWithPID:(int)arg1 flags:(unsigned)arg2 reason:(unsigned)arg3 name:(id)arg4 withHandler:(/*^block*/id)arg5 ;
-(BOOL)isValid;
-(unsigned)reason;
-(id)invalidationHandler;
-(void)setInvalidationHandler:(id)arg1 ;
-(unsigned)flags;
@end

