/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class AVPlayerLayer;

@interface IMAVExternalVideoView : UIView {

	AVPlayerLayer* _videoLayer;

}

@property (nonatomic,retain) AVPlayerLayer * videoLayer;              //@synthesize videoLayer=_videoLayer - In the implementation block
-(void)dealloc;
-(void)layoutSublayersOfLayer:(id)arg1 ;
-(AVPlayerLayer *)videoLayer;
-(void)setVideoLayer:(AVPlayerLayer *)arg1 ;
@end

