/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class AVPlayer, AVPlayerLayer;

@interface IMAVPlayerLayerView : UIView

@property (nonatomic,retain) AVPlayer * player; 
@property (nonatomic,readonly) AVPlayerLayer * videoLayer; 
+(id)playerLayerViewWithPlayer:(id)arg1 ;
+(Class)layerClass;
-(id)initWithPlayer:(id)arg1 ;
-(AVPlayerLayer *)videoLayer;
-(AVPlayer *)player;
-(void)setPlayer:(AVPlayer *)arg1 ;
@end

