/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIAccessibilityElement.h>

@interface IMAXMoreLabelElement : UIAccessibilityElement {

	id _delegate;

}

@property (assign,nonatomic) id delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithAccessibilityContainer:(id)arg1 delegate:(id)arg2 ;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(CGRect)accessibilityFrame;
-(id)accessibilityLabel;
@end

