/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class IMTopShelf, NSString, NSOperationQueue, IMBookshelfImageConfiguration;

@interface IMBookshelfImageGenerator : NSObject {

	IMTopShelf* _portraitTopShelf;
	IMTopShelf* _alternatePortraitTopShelf;
	IMTopShelf* _landscapeTopShelf;
	IMTopShelf* _alternateLandscapeTopShelf;
	NSString* _outputDirectory;
	long long _numberOfShelves;
	NSOperationQueue* _writeQueue;
	BOOL _useSynchronousWrites;
	double _shelfHeight;
	IMBookshelfImageConfiguration* _configuration;

}

@property (nonatomic,retain) NSString * outputDirectory;                                 //@synthesize outputDirectory=_outputDirectory - In the implementation block
@property (assign,nonatomic) long long numberOfShelves;                                  //@synthesize numberOfShelves=_numberOfShelves - In the implementation block
@property (assign,nonatomic) BOOL useSynchronousWrites;                                  //@synthesize useSynchronousWrites=_useSynchronousWrites - In the implementation block
@property (assign,nonatomic) double shelfHeight;                                         //@synthesize shelfHeight=_shelfHeight - In the implementation block
@property (nonatomic,retain) IMBookshelfImageConfiguration * configuration;              //@synthesize configuration=_configuration - In the implementation block
+(BOOL)writeCgImageRef:(CGImageRef)arg1 toPath:(id)arg2 type:(CFStringRef)arg3 ;
-(long long)numberOfShelves;
-(void)setNumberOfShelves:(long long)arg1 ;
-(void)setShelfHeight:(double)arg1 ;
-(void)createWithSize:(CGSize)arg1 isPad:(BOOL)arg2 isPortrait:(BOOL)arg3 scale:(double)arg4 ;
-(void)createWithSize:(CGSize)arg1 isPad:(BOOL)arg2 isPortrait:(BOOL)arg3 scale:(double)arg4 alternate:(BOOL)arg5 ;
-(double)shelfHeight;
-(id)alternatePortraitTopShelfImage;
-(id)alternateLandscapeTopShelfImage;
-(id)portraitTopShelfImage;
-(id)landscapeTopShelfImage;
-(id)alternatePortraitImageArray;
-(id)alternateLandscapeImageArray;
-(id)portraitImageArray;
-(id)landscapeImageArray;
-(void)setOutputDirectory:(NSString *)arg1 ;
-(void)_releaseImages;
-(NSString *)outputDirectory;
-(BOOL)useSynchronousWrites;
-(void)setUseSynchronousWrites:(BOOL)arg1 ;
-(id)init;
-(void)dealloc;
-(void)setConfiguration:(IMBookshelfImageConfiguration *)arg1 ;
-(IMBookshelfImageConfiguration *)configuration;
-(void)memoryWarning:(id)arg1 ;
@end

