/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/IMCloudSyncOperationDelegate.h>
#import <Podcasts/IMCloudsyncDeserializeOperationDelegate.h>

@protocol IMCloudSyncControllerDelegate, OS_dispatch_queue;
@class NSURL, NSString, IMCloudSyncStoreAuthenticationController, NSMutableArray, IMCloudSyncClampsController, IMCloudSyncTransaction, NSOperationQueue, IMCloudSyncDeserializer, NSObject;

@interface IMCloudSyncController : NSObject <IMCloudSyncOperationDelegate, IMCloudsyncDeserializeOperationDelegate> {

	id<IMCloudSyncControllerDelegate> _delegate;
	NSURL* _defaultGetURL;
	NSURL* _defaultSetURL;
	NSString* _defaultDomain;
	BOOL _enabled;
	IMCloudSyncStoreAuthenticationController* _authenticationController;
	BOOL _resolvingError;
	NSMutableArray* _pendingTransactions;
	IMCloudSyncClampsController* _clampsController;
	IMCloudSyncTransaction* _currentTransaction;
	NSOperationQueue* _operationQueue;
	IMCloudSyncDeserializer* _currentDeserializer;
	NSObject*<OS_dispatch_queue> _dispatchQueue;
	unsigned long long _backgroundTaskIdentifier;

}

@property (nonatomic,retain) NSMutableArray * pendingTransactions;                                   //@synthesize pendingTransactions=_pendingTransactions - In the implementation block
@property (nonatomic,retain) IMCloudSyncTransaction * currentTransaction;                            //@synthesize currentTransaction=_currentTransaction - In the implementation block
@property (nonatomic,retain) IMCloudSyncClampsController * clampsController;                         //@synthesize clampsController=_clampsController - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;                                      //@synthesize operationQueue=_operationQueue - In the implementation block
@property (nonatomic,retain) IMCloudSyncDeserializer * currentDeserializer;                          //@synthesize currentDeserializer=_currentDeserializer - In the implementation block
@property (assign,getter=isResolvingError,nonatomic) BOOL resolvingError;                            //@synthesize resolvingError=_resolvingError - In the implementation block
@property (assign,nonatomic) NSObject*<OS_dispatch_queue> dispatchQueue;                             //@synthesize dispatchQueue=_dispatchQueue - In the implementation block
@property (assign,nonatomic) unsigned long long backgroundTaskIdentifier;                            //@synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier - In the implementation block
@property (assign) id<IMCloudSyncControllerDelegate> delegate;                                       //@synthesize delegate=_delegate - In the implementation block
@property (retain) NSURL * defaultGetURL;                                                            //@synthesize defaultGetURL=_defaultGetURL - In the implementation block
@property (retain) NSURL * defaultSetURL;                                                            //@synthesize defaultSetURL=_defaultSetURL - In the implementation block
@property (copy) NSString * defaultDomain;                                                           //@synthesize defaultDomain=_defaultDomain - In the implementation block
@property (getter=isEnabled) BOOL enabled;                                                           //@synthesize enabled=_enabled - In the implementation block
@property (retain) IMCloudSyncStoreAuthenticationController * authenticationController;              //@synthesize authenticationController=_authenticationController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)defaultDomain;
-(NSURL *)defaultGetURL;
-(NSURL *)defaultSetURL;
-(void)resolveError:(id)arg1 resolution:(int)arg2 ;
-(void)setDefaultDomain:(NSString *)arg1 ;
-(void)setDefaultGetURL:(NSURL *)arg1 ;
-(void)setDefaultSetURL:(NSURL *)arg1 ;
-(IMCloudSyncClampsController *)clampsController;
-(void)_processPendingTransactions;
-(void)_cancelAllTransactions:(id)arg1 ;
-(void)_scheduleTransaction:(id)arg1 ;
-(void)_transactionDidFail:(id)arg1 withError:(id)arg2 ;
-(void)_cancelTransaction:(id)arg1 error:(id)arg2 ;
-(void)_processCurrentTransaction;
-(BOOL)_authenticationCanProcessTransaction:(id)arg1 error:(id*)arg2 ;
-(id)_requestForTransaction:(id)arg1 ;
-(BOOL)_canScheduleTransaction:(id)arg1 error:(id*)arg2 ;
-(void)_addPendingTransaction:(id)arg1 ;
-(BOOL)_isEnabledForTransaction:(id)arg1 error:(id*)arg2 ;
-(BOOL)_isTransactionValid:(id)arg1 error:(id*)arg2 ;
-(BOOL)_clampsCanScheduleTransaction:(id)arg1 error:(id*)arg2 ;
-(void)setCurrentDeserializer:(IMCloudSyncDeserializer *)arg1 ;
-(void)setResolvingError:(BOOL)arg1 ;
-(void)_errorResolutionRetry:(id)arg1 ;
-(void)_errorResolutionCancel:(id)arg1 ;
-(void)_errorResolutionDefault:(id)arg1 ;
-(void)_processOperationOutput:(id)arg1 operationAuthenticated:(BOOL)arg2 ;
-(void)_currentTransactionDidFinish;
-(IMCloudSyncDeserializer *)currentDeserializer;
-(void)deserializeOperationDidFinish:(id)arg1 shouldReschedule:(BOOL)arg2 ;
-(id)scheduleGetTransactionWithKeys:(id)arg1 processor:(id)arg2 ;
-(id)scheduleSetTransactionWithKeys:(id)arg1 processor:(id)arg2 ;
-(id)_scheduleTransactionWithType:(int)arg1 URL:(id)arg2 keys:(id)arg3 processor:(id)arg4 ;
-(BOOL)_requireUserOptInForTransaction:(id)arg1 ;
-(void)cloudSyncOperation:(id)arg1 scheduleURLOperation:(id)arg2 ;
-(void)cloudSyncOperationOperationDidFinish:(id)arg1 ;
-(void)setClampsController:(IMCloudSyncClampsController *)arg1 ;
-(void)_beginBackgroundTask;
-(id)init;
-(void)setDelegate:(id<IMCloudSyncControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<IMCloudSyncControllerDelegate>)delegate;
-(void)reset;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(NSOperationQueue *)operationQueue;
-(void)performBlockAndWait:(/*^block*/id)arg1 ;
-(void)performBlock:(/*^block*/id)arg1 ;
-(void)setBackgroundTaskIdentifier:(unsigned long long)arg1 ;
-(unsigned long long)backgroundTaskIdentifier;
-(IMCloudSyncStoreAuthenticationController *)authenticationController;
-(void)_endBackgroundTask;
-(void)operation:(id)arg1 didReceiveResponse:(id)arg2 ;
-(void)operation:(id)arg1 finishedWithOutput:(id)arg2 ;
-(BOOL)isIdle;
-(void)operation:(id)arg1 failedWithError:(id)arg2 ;
-(NSObject*<OS_dispatch_queue>)dispatchQueue;
-(void)setDispatchQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)scheduleTransaction:(id)arg1 ;
-(BOOL)_delegateShouldScheduleTransaction:(id)arg1 error:(id*)arg2 ;
-(void)_delegateTransactionDidFinish:(id)arg1 ;
-(BOOL)_delegateTransactionDidFail:(id)arg1 withError:(id)arg2 ;
-(void)_resolveError:(id)arg1 resolution:(int)arg2 ;
-(void)cancelScheduledTransaction:(id)arg1 ;
-(IMCloudSyncTransaction *)currentTransaction;
-(void)setCurrentTransaction:(IMCloudSyncTransaction *)arg1 ;
-(BOOL)isResolvingError;
-(void)setAuthenticationController:(IMCloudSyncStoreAuthenticationController *)arg1 ;
-(NSMutableArray *)pendingTransactions;
-(void)setPendingTransactions:(NSMutableArray *)arg1 ;
@end

