/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class NSMutableArray;

@interface IMDatabaseCursor : NSObject {

	NSMutableArray* _results;
	int _numColumns;
	sqlite3_stmtRef _statement;
	id* _columnNames;
	id* _columnTypes;
	BOOL _closed;

}
-(id)nextRowAsArray;
-(id)nextRowAsDictionary;
-(id)_undeclaredTypeForColumnIndex:(int)arg1 ;
-(id)initWithQuery:(id)arg1 databaseHandle:(id)arg2 ;
-(void)dealloc;
-(BOOL)reset;
-(BOOL)close;
-(id)results;
-(id)initWithStatement:(sqlite3_stmtRef)arg1 ;
-(id)columnTypeAtIndex:(long long)arg1 ;
-(sqlite3_stmtRef)statement;
-(long long)columnCount;
-(id)columnNameAtIndex:(long long)arg1 ;
-(long long)rowCount;
@end

