/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <Podcasts/Podcasts-Structs.h>
@class IMMemoryCache, NSString, NSObject, NSCache;

@interface IMImageCache : NSObject {

	IMMemoryCache* _memoryCache;
	NSString* _persistentCachePath;
	NSObject*<OS_dispatch_queue> _downloadQueue;
	NSString* _defaultType;
	NSCache* _metadataCache;

}

@property (nonatomic,retain) NSString * defaultType;              //@synthesize defaultType=_defaultType - In the implementation block
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 ;
-(id)initWithIdentifier:(id)arg1 basePath:(id)arg2 memorySize:(long long)arg3 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 persist:(BOOL)arg4 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 type:(id)arg3 persist:(BOOL)arg4 properties:(id)arg5 ;
-(void)flushPersistentCache;
-(void)removeImageForKey:(id)arg1 synchronous:(BOOL)arg2 ;
-(id)_fetchImageForKey:(id)arg1 forceDecode:(BOOL)arg2 ;
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 forceDecode:(BOOL)arg3 ;
-(id)_keyForSize:(CGSize)arg1 withBaseKey:(id)arg2 ;
-(id)imageForKey:(id)arg1 forceDecode:(BOOL)arg2 ;
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 resizeOptions:(int)arg3 forceDecode:(BOOL)arg4 ;
-(void)imageForKey:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 options:(int)arg5 ;
-(void)addImageFromURL:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 ;
-(void)addImageFromURL:(id)arg1 key:(id)arg2 size:(CGSize)arg3 completionBlock:(/*^block*/id)arg4 queue:(id)arg5 ;
-(BOOL)hasImageForKey:(id)arg1 ;
-(id)initWithIdentifier:(id)arg1 memorySize:(long long)arg2 ;
-(void)removeImageWithRootKey:(id)arg1 ;
-(id)imageForKey:(id)arg1 size:(CGSize)arg2 resizeOptions:(int)arg3 ;
-(void)imageForKey:(id)arg1 completionBlock:(/*^block*/id)arg2 queue:(id)arg3 ;
-(void)imageForKey:(id)arg1 size:(CGSize)arg2 completionBlock:(/*^block*/id)arg3 queue:(id)arg4 ;
-(void)addImageFromURL:(id)arg1 completionBlock:(/*^block*/id)arg2 queue:(id)arg3 ;
-(BOOL)hasImageForKey:(id)arg1 withSize:(CGSize)arg2 ;
-(void)getImageMetadataForKey:(id)arg1 size:(CGSize*)arg2 scale:(double*)arg3 ;
-(NSString *)defaultType;
-(void)setDefaultType:(NSString *)arg1 ;
-(void)dealloc;
-(BOOL)isEmpty;
-(void)removeImageForKey:(id)arg1 ;
-(id)imageForKey:(id)arg1 ;
-(void)setImage:(id)arg1 forKey:(id)arg2 ;
-(void)flushMemoryCache;
-(void)flushAllCaches;
@end

