/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/IMLibraryBooksViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITextFieldDelegate.h>

@class UITableView, IMToolbar, NSString;

@interface IMLibraryBooksListViewController : IMLibraryBooksViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate> {

	UITableView* _tableView;
	IMToolbar* _sortingToolbar;
	BOOL _changeIsUserDriven;
	BOOL _automaticallyAdjustsTableViewForKeyboard;

}

@property (assign,nonatomic) BOOL automaticallyAdjustsTableViewForKeyboard;              //@synthesize automaticallyAdjustsTableViewForKeyboard=_automaticallyAdjustsTableViewForKeyboard - In the implementation block
@property (nonatomic,retain) UITableView * tableView;                                    //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) IMToolbar * sortingToolbar;                                 //@synthesize sortingToolbar=_sortingToolbar - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dataSourceWillChangeContent:(id)arg1 ;
-(void)dataSource:(id)arg1 didChangeSectionAtIndex:(unsigned long long)arg2 forChangeType:(int)arg3 ;
-(void)dataSource:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(int)arg4 newIndexPath:(id)arg5 ;
-(void)dataSourceDidChangeContent:(id)arg1 ;
-(void)releaseViews;
-(id)embeddedToolbar;
-(void)repopulateDisplay;
-(void)setEmbeddedToolbarItems:(id)arg1 ;
-(BOOL)isBookFullyVisible:(id)arg1 ;
-(void)scrollToMakeObjectVisible:(id)arg1 ;
-(void)_updateFrames;
-(BOOL)isSectioned;
-(BOOL)automaticallyAdjustsTableViewForKeyboard;
-(IMToolbar *)sortingToolbar;
-(void)setSortingToolbar:(IMToolbar *)arg1 ;
-(void)setAutomaticallyAdjustsTableViewForKeyboard:(BOOL)arg1 ;
-(BOOL)wantsCollectionAnimation;
-(void)setMainPredicate:(id)arg1 ;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(BOOL)shouldAutorotateToInterfaceOrientation:(long long)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)setTableView:(UITableView *)arg1 ;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(UITableView *)tableView;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(id)searchField;
-(void)keyboardWillShow:(id)arg1 ;
-(void)keyboardWillHide:(id)arg1 ;
-(id)assetAtIndexPath:(id)arg1 ;
@end

