/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, NSMutableArray;

@interface IMLibraryTiledBackgroundView : UIView {

	CGPoint _offset;
	double _height;
	NSArray* _images;
	NSMutableArray* _tiles;
	CGSize _tileSize;

}

@property (assign,nonatomic) CGPoint offset;                //@synthesize offset=_offset - In the implementation block
@property (assign,nonatomic) CGSize tileSize;               //@synthesize tileSize=_tileSize - In the implementation block
@property (assign,nonatomic) double height;                 //@synthesize height=_height - In the implementation block
@property (nonatomic,retain) NSArray * images;              //@synthesize images=_images - In the implementation block
-(void)setTileCount:(long long)arg1 viewProvider:(/*^block*/id)arg2 ;
-(void)_adjustRowLayout;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(NSArray *)images;
-(void)setImages:(NSArray *)arg1 ;
-(double)height;
-(void)setTileSize:(CGSize)arg1 ;
-(void)setOffset:(CGPoint)arg1 ;
-(CGPoint)offset;
-(CGSize)tileSize;
-(void)setHeight:(double)arg1 ;
@end

