/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMMutableAttachmentInfoAEAnnotation <IMAttachmentInfoAEAnnotation>
@required
-(void)setAEAnnotationUuid:(id)arg1;
-(void)setAEAnnotationAssetID:(id)arg1;
-(void)setAEAnnotationManagedObjectID:(id)arg1;

@end

