/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class NSString, NSDictionary;

@interface IMNowPlayingContentLabel : UIView {

	NSString* _fullString;
	NSDictionary* _stringAttributes;
	CTFramesetterRef _framesetter;
	CTFrameRef _frame;
	BOOL _highlighted;

}

@property (assign,nonatomic) BOOL highlighted;              //@synthesize highlighted=_highlighted - In the implementation block
-(id)stringAttributes;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)arg1 ;
-(void)dealloc;
-(void)tintColorDidChange;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)update;
-(BOOL)highlighted;
@end

