/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIControl.h>

@class UIImageView;

@interface IMQuickScroller : UIControl {

	float _value;
	UIImageView* _background;
	UIImageView* _foreground;
	BOOL _userScrolling;

}

@property (assign,nonatomic) float value;                       //@synthesize value=_value - In the implementation block
@property (nonatomic,readonly) BOOL userScrolling;              //@synthesize userScrolling=_userScrolling - In the implementation block
+(id)backgroundForSize:(CGSize)arg1 ;
+(id)foregroundForSize:(CGSize)arg1 ;
-(void)updateValueForTouch:(id)arg1 ;
-(BOOL)userScrolling;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(float)value;
-(void)setValue:(float)arg1 ;
-(void)cancelTrackingWithEvent:(id)arg1 ;
-(BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
-(void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2 ;
@end

