/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UITextField.h>

@class UIColor;

@interface IMSearchField : UITextField {

	BOOL _xTapped;
	UIColor* _placeholderTextColor;

}

@property (assign,nonatomic) BOOL xTapped;                                //@synthesize xTapped=_xTapped - In the implementation block
@property (nonatomic,retain) UIColor * placeholderTextColor;              //@synthesize placeholderTextColor=_placeholderTextColor - In the implementation block
-(void)setXTapped:(BOOL)arg1 ;
-(BOOL)xTapped;
-(CGPoint)_offsetForMiniBarState:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(BOOL)canBecomeFirstResponder;
-(CGRect)editingRectForBounds:(CGRect)arg1 ;
-(CGRect)textRectForBounds:(CGRect)arg1 ;
-(CGRect)leftViewRectForBounds:(CGRect)arg1 ;
-(CGRect)borderRectForBounds:(CGRect)arg1 ;
-(void)drawPlaceholderInRect:(CGRect)arg1 ;
-(void)setPlaceholderTextColor:(UIColor *)arg1 ;
-(UIColor *)placeholderTextColor;
@end

