/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@class IMSearchField, UIView;

@interface IMSearchTableHeader : UIView {

	IMSearchField* _searchField;
	UIView* _topLineView;
	UIView* _bottomLineView;

}

@property (nonatomic,readonly) IMSearchField * searchField;              //@synthesize searchField=_searchField - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(IMSearchField *)searchField;
@end

