/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMViewControllerTransition.h>

@interface IMSlideTransition : IMViewControllerTransition {

	int _type;

}

@property (assign,nonatomic) int type;              //@synthesize type=_type - In the implementation block
-(void)prepareTransition;
-(void)performTransition;
-(void)cleanupTransition;
-(id)init;
-(void)setType:(int)arg1 ;
-(int)type;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

