/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface IMStack : NSObject {

	NSMutableArray* _array;

}
-(void)pushObjects:(id)arg1 ;
-(id)peekDown:(unsigned long long)arg1 ;
-(id)peek;
-(id)init;
-(void)dealloc;
-(BOOL)isEmpty;
-(id)pop;
-(void)removeAll;
-(void)push:(id)arg1 ;
-(unsigned long long)depth;
@end

