/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@interface IMThumbnailUtilities : NSObject
+(CGSize)proportionalScaleSize:(CGSize)arg1 toDestinationSize:(CGSize)arg2 options:(long long)arg3 ;
+(CGContextRef)newBitmapContextForSize:(CGSize)arg1 ;
+(id)finalizeBitmap:(CGContextRef)arg1 ;
+(id)scaleImage:(id)arg1 toSize:(CGSize)arg2 options:(long long)arg3 ;
@end

