/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/IMOperation.h>

@class IMStopWatch;

@interface IMTimedOperation : IMOperation {

	IMStopWatch* _stopwatch;
	BOOL _shouldReportDuration;

}
-(void)sendStartedMessage;
-(void)sendFinishedMessage;
-(void)setShouldReportDuration:(BOOL)arg1 ;
-(void)sendStartedMessageWithTimerDescription:(id)arg1 ;
-(void)dealloc;
@end

