/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@class NSString, IMBookshelfImageConfiguration, UIImage;

@interface IMTopShelf : NSObject {

	CGSize _size;
	double _scale;
	double _shelfHeight;
	unsigned long long _numberOfShelves;
	BOOL _isPad;
	BOOL _isPortrait;
	BOOL _isAlternate;
	BOOL _useSynchronousWrites;
	NSString* _outputDirectory;
	IMBookshelfImageConfiguration* _configuration;
	CGImage* _shelves[10];
	UIImage* _image;

}
+(id)writeQueue;
-(void)releaseImages;
-(id)initWithSize:(CGSize)arg1 scale:(double)arg2 shelfHeight:(double)arg3 numberOfShelves:(unsigned long long)arg4 isPad:(BOOL)arg5 isPortrait:(BOOL)arg6 isAlternate:(BOOL)arg7 useSynchronousWrites:(BOOL)arg8 outputDirectory:(id)arg9 configuration:(id)arg10 ;
-(id)imageArray;
-(id)_fileNameWithBaseName:(id)arg1 isPad:(BOOL)arg2 isPortrait:(BOOL)arg3 scale:(double)arg4 type:(CFStringRef)arg5 alternate:(BOOL)arg6 modernUI:(BOOL)arg7 ;
-(BOOL)_testImagesExistIsPad:(BOOL)arg1 isPortrait:(BOOL)arg2 scale:(double)arg3 alternate:(BOOL)arg4 ;
-(void)_createWithSize:(CGSize)arg1 scale:(double)arg2 isPad:(BOOL)arg3 isPortrait:(BOOL)arg4 isAlternate:(BOOL)arg5 imagesExist:(BOOL)arg6 modernUI:(BOOL)arg7 ;
-(void)_loadImagesIsPad:(BOOL)arg1 isPortrait:(BOOL)arg2 scale:(double)arg3 alternate:(BOOL)arg4 ;
-(id)_fileNameAtIndex:(long long)arg1 isPad:(BOOL)arg2 isPortrait:(BOOL)arg3 scale:(double)arg4 type:(CFStringRef)arg5 alternate:(BOOL)arg6 modernUI:(BOOL)arg7 ;
-(CGImageRef)copyImageAtPath:(id)arg1 ;
-(void)_reorderShelves:(CGImage*)arg1 ;
-(id)_copyFromCGImage:(CGImageRef)arg1 scale:(double)arg2 ;
-(void)_removeImagesIsPad:(BOOL)arg1 isPortrait:(BOOL)arg2 scale:(double)arg3 alternate:(BOOL)arg4 ;
-(void)dealloc;
-(id)image;
@end

