/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMTransitionParent <NSObject>
@optional
-(BOOL)shouldPerformChildTransition:(id)arg1;
-(void)childTransitionWillStart:(id)arg1;
-(void)childTransitionDidStart:(id)arg1;
-(void)childTransitionDidComplete:(id)arg1 finished:(BOOL)arg2;

@end

