/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMTransition.h>

@protocol IMViewControllerContaining;
@class UIViewController, UIImageView, UIView;

@interface IMViewControllerTransition : IMTransition {

	UIViewController*<IMViewControllerContaining> _fromViewController;
	UIViewController*<IMViewControllerContaining> _toViewController;
	UIImageView* _fromViewSnapshot;
	UIImageView* _toViewSnapshot;

}

@property (nonatomic,readonly) UIView * fromView; 
@property (nonatomic,readonly) UIView * toView; 
@property (nonatomic,retain) UIViewController*<IMViewControllerContaining> fromViewController;              //@synthesize fromViewController=_fromViewController - In the implementation block
@property (nonatomic,retain) UIViewController*<IMViewControllerContaining> toViewController;                //@synthesize toViewController=_toViewController - In the implementation block
@property (nonatomic,retain) UIImageView * fromViewSnapshot;                                                //@synthesize fromViewSnapshot=_fromViewSnapshot - In the implementation block
@property (nonatomic,retain) UIImageView * toViewSnapshot;                                                  //@synthesize toViewSnapshot=_toViewSnapshot - In the implementation block
-(void)setFromViewController:(UIViewController*<IMViewControllerContaining>)arg1 ;
-(void)setToViewController:(UIViewController*<IMViewControllerContaining>)arg1 ;
-(void)setReverse:(BOOL)arg1 ;
-(void)prepareTransition;
-(void)setFromViewSnapshot:(UIImageView *)arg1 ;
-(void)setToViewSnapshot:(UIImageView *)arg1 ;
-(void)loadToView;
-(void)beginAppearanceTransition;
-(void)cleanupTransition;
-(void)performNonAnimatedTransition;
-(int)roleForViewController:(id)arg1 ;
-(CGRect)fillBoundsTargetRect;
-(UIImageView *)fromViewSnapshot;
-(UIImageView *)toViewSnapshot;
-(CATransform3D)fillBoundsScaleTransformFromTransform:(CATransform3D)arg1 sourceRect:(CGRect)arg2 ;
-(id)init;
-(void)dealloc;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)endAppearanceTransition;
-(UIView *)fromView;
-(UIView *)toView;
-(UIViewController*<IMViewControllerContaining>)fromViewController;
-(UIViewController*<IMViewControllerContaining>)toViewController;
-(void)transitionDidEnd;
-(void)beginTransition;
@end

