/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface MTAddPodcastParams : NSObject {

	BOOL _userInitiated;
	NSString* _url;
	NSString* _location;
	long long _storeCollectionId;

}

@property (nonatomic,retain) NSString * url;                           //@synthesize url=_url - In the implementation block
@property (nonatomic,retain) NSString * location;                      //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) long long storeCollectionId;              //@synthesize storeCollectionId=_storeCollectionId - In the implementation block
@property (assign,nonatomic) BOOL userInitiated;                       //@synthesize userInitiated=_userInitiated - In the implementation block
-(long long)storeCollectionId;
-(void)setStoreCollectionId:(long long)arg1 ;
-(id)init;
-(NSString *)url;
-(void)setUrl:(NSString *)arg1 ;
-(BOOL)userInitiated;
-(void)setUserInitiated:(BOOL)arg1 ;
-(NSString *)location;
-(void)setLocation:(NSString *)arg1 ;
@end

