/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTPodcastAndEpisodeProcessor.h>
#import <Podcasts/MTReachabilityObserver.h>

@class MTUuidQueryObserver, NSString;

@interface MTAutoDownloadProcessor : MTPodcastAndEpisodeProcessor <MTReachabilityObserver> {

	BOOL _hasCheckQueued;
	MTUuidQueryObserver* _savedObserver;
	double _lastCheckTime;

}

@property (nonatomic,retain) MTUuidQueryObserver * savedObserver;              //@synthesize savedObserver=_savedObserver - In the implementation block
@property (assign,nonatomic) double lastCheckTime;                             //@synthesize lastCheckTime=_lastCheckTime - In the implementation block
@property (assign,nonatomic) BOOL hasCheckQueued;                              //@synthesize hasCheckQueued=_hasCheckQueued - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)reachabilityChangedFrom:(BOOL)arg1 to:(BOOL)arg2 ;
-(id)podcastPredicate;
-(id)defaultPropertiesThatAffectPredicate;
-(void)setLastCheckTime:(double)arg1 ;
-(void)setSavedObserver:(MTUuidQueryObserver *)arg1 ;
-(MTUuidQueryObserver *)savedObserver;
-(void)_reCheck;
-(void)_lpmDidChange;
-(BOOL)_isLPMEnabled;
-(double)lastCheckTime;
-(BOOL)hasCheckQueued;
-(void)setHasCheckQueued:(BOOL)arg1 ;
-(void)autodownloadEpisodesChanged:(id)arg1 ;
-(id)episodePredicateForPodcast:(id)arg1 ;
-(void)episodeResultsChangedForPodcast:(id)arg1 withDeletedIds:(id)arg2 andInsertIds:(id)arg3 ;
-(void)dealloc;
-(void)start;
@end

