/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTEpisodeListViewController.h>

@class NSMutableOrderedSet, NSString;

@interface MTBasePlaylistEpisodeListViewController : MTEpisodeListViewController {

	NSMutableOrderedSet* _items;
	BOOL _editable;
	NSString* _playlistUuid;
	NSString* _settingsUuid;

}

@property (nonatomic,retain) NSString * playlistUuid;                      //@synthesize playlistUuid=_playlistUuid - In the implementation block
@property (nonatomic,retain) NSString * settingsUuid;                      //@synthesize settingsUuid=_settingsUuid - In the implementation block
@property (assign,getter=isEditable,nonatomic) BOOL editable;              //@synthesize editable=_editable - In the implementation block
-(void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3 ;
-(void)playEpisodeAtIndexPath:(id)arg1 ;
-(void)markSelectedItems:(BOOL)arg1 ;
-(void)markSelectedItemsAsSaved:(BOOL)arg1 ;
-(void)setSettingsUuid:(NSString *)arg1 ;
-(void)setPlaylistUuid:(NSString *)arg1 ;
-(void)removeSelectedItems:(id)arg1 ;
-(NSString *)playlistUuid;
-(void)markEpisodesAtIndexPaths:(id)arg1 asSaved:(BOOL)arg2 ;
-(unsigned long long)indexOfUuid:(id)arg1 ;
-(void)updateTableWithEpisodes:(id)arg1 originalItems:(id)arg2 animated:(BOOL)arg3 section:(long long)arg4 ;
-(NSString *)settingsUuid;
-(id)metricsName;
-(id)metricDataSource;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5 ;
-(void)controllerDidChangeContent:(id)arg1 ;
-(id)indexPathForObject:(id)arg1 ;
-(void)reloadData;
-(void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(BOOL)isEditable;
-(id)items;
-(void)setEditable:(BOOL)arg1 ;
-(id)initWithPlaylist:(id)arg1 ;
-(id)initWithPredicate:(id)arg1 ;
-(id)objectAtIndexPath:(id)arg1 ;
-(void)_loadItems;
@end

