/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTPlayerManifest.h>

@class MTPlayerManifest;

@interface MTCompositeManifest : MTPlayerManifest {

	BOOL _isPlayingFromUpNext;
	MTPlayerManifest* _currentManifest;
	MTPlayerManifest* _upNextManifest;
	MTPlayerManifest* _userManifest;

}

@property (nonatomic,retain) MTPlayerManifest * currentManifest;              //@synthesize currentManifest=_currentManifest - In the implementation block
@property (nonatomic,retain) MTPlayerManifest * upNextManifest;               //@synthesize upNextManifest=_upNextManifest - In the implementation block
@property (nonatomic,retain) MTPlayerManifest * userManifest;                 //@synthesize userManifest=_userManifest - In the implementation block
@property (nonatomic,readonly) BOOL isPlayingFromUpNext;                      //@synthesize isPlayingFromUpNext=_isPlayingFromUpNext - In the implementation block
-(MTPlayerManifest *)upNextManifest;
-(void)_playerManifestDidChangeContent:(id)arg1 ;
-(void)_setupManifestDefaults;
-(void)_determineManifest:(id*)arg1 scalledIndex:(unsigned long long*)arg2 forIndex:(unsigned long long)arg3 ;
-(void)setCurrentManifest:(MTPlayerManifest *)arg1 ;
-(void)notifyCurrentItemDidChange;
-(BOOL)isPlayingFromManifest:(id)arg1 ;
-(id)initWithUpNextManifest:(id)arg1 userManifest:(id)arg2 ;
-(BOOL)isPlayingFromUpNext;
-(void)setUpNextManifest:(MTPlayerManifest *)arg1 ;
-(void)setUserManifest:(MTPlayerManifest *)arg1 ;
-(id)metricsContentIdentifier;
-(id)metricsAdditionalData;
-(MTPlayerManifest *)userManifest;
-(void)dealloc;
-(unsigned long long)count;
-(id)objectAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)currentIndex;
-(id)currentItem;
-(id)activity;
-(void)_load;
-(void)setCurrentIndex:(unsigned long long)arg1 ;
-(MTPlayerManifest *)currentManifest;
-(void)_currentItemDidChange:(id)arg1 ;
@end

