/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSMutableArray, NSManagedObjectContext, NSPredicate, NSMutableSet, NSString;

@interface MTEntityUpdaterCache : NSObject {

	NSArray* _properties;
	NSMutableArray* _objectsByProperty;
	NSArray* _propertiesToFetch;
	NSManagedObjectContext* _ctx;
	NSPredicate* _predicate;
	NSMutableSet* _unvisited;
	NSString* _entityName;
	/*^block*/id _allowKeyForValue;

}

@property (nonatomic,copy) id allowKeyForValue;              //@synthesize allowKeyForValue=_allowKeyForValue - In the implementation block
-(id)initWithPredicate:(id)arg1 entityName:(id)arg2 ctx:(id)arg3 properties:(id)arg4 fetchProperties:(id)arg5 ;
-(id)propertyDictionaryForSearchItem:(id)arg1 ;
-(void)addEntityToCache:(id)arg1 ;
-(void)_buildMap;
-(void)_addDictionary:(id)arg1 ;
-(void)enumerateUnvisitedItemUuids:(/*^block*/id)arg1 ;
-(id)allowKeyForValue;
-(void)setAllowKeyForValue:(id)arg1 ;
@end

