/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTSingleton.h>
#import <libobjc.A.dylib/NSCacheDelegate.h>

@class NSCache, NSString;

@interface MTEpisodeDescriptionCache : MTSingleton <NSCacheDelegate> {

	NSCache* _descriptionCache;
	NSCache* _episodeCache;

}

@property (nonatomic,retain) NSCache * descriptionCache;              //@synthesize descriptionCache=_descriptionCache - In the implementation block
@property (nonatomic,retain) NSCache * episodeCache;                  //@synthesize episodeCache=_episodeCache - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSCache *)episodeCache;
-(void)setEpisodeCache:(NSCache *)arg1 ;
-(id)descriptionForEpisode:(id)arg1 ;
-(id)descriptionBodyTextForEpisode:(id)arg1 html:(BOOL)arg2 withAttributes:(id)arg3 ;
-(void)updateCacheForEpisode:(id)arg1 ;
-(id)descriptionCacheForEpisodeUuid:(id)arg1 ;
-(id)descriptionKeyForOptions:(unsigned long long)arg1 unavailableReason:(unsigned long long)arg2 ;
-(id)descriptionTextForEpisode:(id)arg1 options:(unsigned long long)arg2 ;
-(id)descriptionForEpisode:(id)arg1 options:(unsigned long long)arg2 ;
-(id)metadataFooterForEpisode:(id)arg1 includingDuration:(BOOL)arg2 ;
-(NSCache *)descriptionCache;
-(id)dependantPropertyKeys;
-(id)descriptionPrefixTextForEpisode:(id)arg1 options:(unsigned long long)arg2 trailingNewline:(BOOL)arg3 ;
-(id)descriptionFooterTextForEpisode:(id)arg1 includesDuration:(BOOL)arg2 hasBodyText:(BOOL)arg3 unavailableReason:(unsigned long long)arg4 ;
-(id)createVideoGlyphAttributedString;
-(id)descriptionPrefixTextForPlayerItem:(id)arg1 options:(unsigned long long)arg2 trailingNewline:(BOOL)arg3 ;
-(id)metadataHeaderForEpisode:(id)arg1 ;
-(id)metadataFooterForEpisode:(id)arg1 ;
-(id)metadataHeaderForPlayerItem:(id)arg1 ;
-(void)setDescriptionCache:(NSCache *)arg1 ;
-(id)init;
-(void)dealloc;
-(void)invalidate;
-(void)cache:(id)arg1 willEvictObject:(id)arg2 ;
@end

