/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSFetchedResultsControllerDelegate.h>
#import <Podcasts/MTFetchedResultsControllerProtocol.h>

@protocol NSFetchedResultsControllerDelegate;
@class NSFetchRequest, NSArray, NSManagedObjectContext, NSFetchedResultsController, NSMutableDictionary, NSMutableArray, NSString;

@interface MTFetchedResultsController : NSObject <NSFetchedResultsControllerDelegate, MTFetchedResultsControllerProtocol> {

	NSFetchedResultsController* _frc;
	NSMutableDictionary* _propertyCache;
	NSMutableArray* _changes;
	NSArray* _propertyKeys;
	NSManagedObjectContext* _managedObjectContext;
	id<NSFetchedResultsControllerDelegate> _delegate;

}

@property (nonatomic,readonly) NSFetchRequest * fetchRequest; 
@property (nonatomic,copy) NSArray * propertyKeys;                                                //@synthesize propertyKeys=_propertyKeys - In the implementation block
@property (nonatomic,readonly) NSManagedObjectContext * managedObjectContext;                     //@synthesize managedObjectContext=_managedObjectContext - In the implementation block
@property (nonatomic,readonly) NSArray * fetchedObjects; 
@property (assign,nonatomic,__weak) id<NSFetchedResultsControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(BOOL)_hasManagedObjectChanged:(id)arg1 ;
-(void)_updateCacheWithManagedObject:(id)arg1 ;
-(void)_removeObjectFromCacheWithId:(id)arg1 ;
-(id)_dictionaryForObject:(id)arg1 ;
-(id)_dictionaryFromCacheForObjectID:(id)arg1 ;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5 ;
-(void)controllerDidChangeContent:(id)arg1 ;
-(void)controllerWillChangeContent:(id)arg1 ;
-(id)initWithFetchRequest:(id)arg1 managedObjectContext:(id)arg2 sectionNameKeyPath:(id)arg3 cacheName:(id)arg4 ;
-(BOOL)performFetch:(id*)arg1 ;
-(id)indexPathForObject:(id)arg1 ;
-(void)setDelegate:(id<NSFetchedResultsControllerDelegate>)arg1 ;
-(id<NSFetchedResultsControllerDelegate>)delegate;
-(NSManagedObjectContext *)managedObjectContext;
-(NSFetchRequest *)fetchRequest;
-(NSArray *)fetchedObjects;
-(id)objectAtIndexPath:(id)arg1 ;
-(NSArray *)propertyKeys;
-(void)setPropertyKeys:(NSArray *)arg1 ;
@end

