/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel;

@interface MTGenericSettingsFooterLabelView : UIView {

	BOOL _topAlignLabel;
	UILabel* _label;

}

@property (nonatomic,retain) UILabel * label;                 //@synthesize label=_label - In the implementation block
@property (assign,nonatomic) BOOL topAlignLabel;              //@synthesize topAlignLabel=_topAlignLabel - In the implementation block
+(double)labelInset;
-(void)_setupLabelWithFont:(id)arg1 ;
-(BOOL)topAlignLabel;
-(BOOL)_isInDarkMode;
-(void)setTopAlignLabel:(BOOL)arg1 ;
-(void)layoutSubviews;
-(void)traitCollectionDidChange:(id)arg1 ;
-(UILabel *)label;
-(void)setLabel:(UILabel *)arg1 ;
-(void)_updateColors;
-(id)initWithFont:(id)arg1 ;
@end

