/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MTCollectionViewCell.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <Podcasts/MTCellProtocol.h>

@class UIView, MTArtworkView, MTLabelStackView, NSString;

@interface MTGenericCollectionCell : MTCollectionViewCell <UIScrollViewDelegate, MTCellProtocol> {

	BOOL _showsArtwork;
	UIView* _sideView;
	MTArtworkView* _artworkView;
	MTLabelStackView* _textStackView;

}

@property (nonatomic,retain) MTArtworkView * artworkView;                   //@synthesize artworkView=_artworkView - In the implementation block
@property (nonatomic,retain) MTLabelStackView * textStackView;              //@synthesize textStackView=_textStackView - In the implementation block
@property (assign,nonatomic) BOOL showsArtwork;                             //@synthesize showsArtwork=_showsArtwork - In the implementation block
@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * subtitle; 
@property (nonatomic,retain) NSString * artworkKey; 
@property (nonatomic,retain) UIView * sideView;                             //@synthesize sideView=_sideView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)estimatedHeight;
+(BOOL)showsArtwork;
+(double)preferredContentWidth;
+(CGSize)artworkSizeForViewWidth:(double)arg1 ;
+(Class)textStackViewClass;
+(id)reuseIdentifier;
+(double)maxHeight;
+(double)heightForWidth:(double)arg1 ;
-(void)configureSubviews;
-(void)updateWithObject:(id)arg1 ;
-(void)setSideView:(UIView *)arg1 ;
-(void)setShowsArtwork:(BOOL)arg1 ;
-(BOOL)showsArtwork;
-(void)setArtworkKey:(NSString *)arg1 ;
-(MTLabelStackView *)textStackView;
-(NSString *)artworkKey;
-(CGRect)artworkFrameForContentViewSize:(CGSize)arg1 ;
-(CGRect)sideViewFrameForContentViewSize:(CGSize)arg1 ;
-(UIView *)sideView;
-(CGRect)textStackFrameForContentViewSize:(CGSize)arg1 artworkFrame:(CGRect)arg2 sideViewFrame:(CGRect)arg3 ;
-(double)textViewMinXForArtworkFrame:(CGRect)arg1 sideViewFrame:(CGRect)arg2 ;
-(double)textViewMaxXForArtworkFrame:(CGRect)arg1 sideViewFrame:(CGRect)arg2 ;
-(void)setTextStackView:(MTLabelStackView *)arg1 ;
-(void)layoutSubviews;
-(void)setTitle:(NSString *)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(NSString *)title;
-(void)prepareForReuse;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(MTArtworkView *)artworkView;
-(void)updateFonts;
-(void)updateColors;
-(void)setArtworkView:(MTArtworkView *)arg1 ;
@end

