/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTStationsViewController.h>

@protocol MTEpisodeListViewControllerDelegate;
@class NSIndexPath, NSString;

@interface MTiTunesFolderViewController : MTStationsViewController {

	NSIndexPath* _lastSelectedIndexPath;
	BOOL _folder;
	NSString* _playlistUuid;
	id<MTEpisodeListViewControllerDelegate> _selectionDelegate;

}

@property (assign,getter=isFolder,nonatomic) BOOL folder;                                                   //@synthesize folder=_folder - In the implementation block
@property (nonatomic,retain) NSString * playlistUuid;                                                       //@synthesize playlistUuid=_playlistUuid - In the implementation block
@property (assign,nonatomic,__weak) id<MTEpisodeListViewControllerDelegate> selectionDelegate;              //@synthesize selectionDelegate=_selectionDelegate - In the implementation block
-(void)restoreSelection;
-(void)setPlaylistUuid:(NSString *)arg1 ;
-(NSString *)playlistUuid;
-(void)iTunesFoldersAreNotRefreshable;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(id)initWithPlaylist:(id)arg1 ;
-(id<MTEpisodeListViewControllerDelegate>)selectionDelegate;
-(BOOL)isFolder;
-(void)setFolder:(BOOL)arg1 ;
-(void)setSelectionDelegate:(id<MTEpisodeListViewControllerDelegate>)arg1 ;
@end

