/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUIJSITunesStore.h>
#import <Podcasts/MTJSITunesStore.h>

@protocol MTJSITunesStore <JSExport>
@required
-(void)playMedia:(id)arg1 :(id)arg2;

@end


@interface MTJSITunesStore : SKUIJSITunesStore <MTJSITunesStore>
-(void)download:(id)arg1 ;
-(void)playMedia:(id)arg1 :(id)arg2 ;
@end

