/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <UIKit/UIView.h>

@protocol MTLabelStackViewDelegate;
@class NSCache, NSString, UIColor, UILabel;

@interface MTLabelStackView : UIView {

	BOOL _heightWillChange;
	NSCache* _textSizeCache;
	BOOL _enabled;
	NSString* _titleTextStyle;
	NSString* _subtitleTextStyle;
	UIColor* _titleTextColor;
	UIColor* _subtitleTextColor;
	id<MTLabelStackViewDelegate> _delegate;
	double _subtitleMaxWidth;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;

}

@property (nonatomic,retain) UILabel * titleLabel;                                      //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UILabel * subtitleLabel;                                   //@synthesize subtitleLabel=_subtitleLabel - In the implementation block
@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * subtitle; 
@property (assign,nonatomic,__weak) id<MTLabelStackViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned long long titleNumberOfLines; 
@property (assign,nonatomic) unsigned long long subtitleNumberOfLines; 
@property (nonatomic,retain) NSString * titleTextStyle;                                 //@synthesize titleTextStyle=_titleTextStyle - In the implementation block
@property (nonatomic,retain) NSString * subtitleTextStyle;                              //@synthesize subtitleTextStyle=_subtitleTextStyle - In the implementation block
@property (nonatomic,retain) UIColor * titleTextColor;                                  //@synthesize titleTextColor=_titleTextColor - In the implementation block
@property (nonatomic,retain) UIColor * subtitleTextColor;                               //@synthesize subtitleTextColor=_subtitleTextColor - In the implementation block
@property (assign,nonatomic) double subtitleMaxWidth;                                   //@synthesize subtitleMaxWidth=_subtitleMaxWidth - In the implementation block
@property (assign,getter=isEnabled,nonatomic) BOOL enabled;                             //@synthesize enabled=_enabled - In the implementation block
+(unsigned long long)defaultTitleNumberOfLines;
+(unsigned long long)defaultSubtitleNumberOfLines;
+(double)maxHeightForTitleNumberOfLines:(unsigned long long)arg1 subtitleNumberOfLines:(unsigned long long)arg2 ;
+(id)defaultTitleFont;
+(id)defaultSubtitleFont;
+(double)distanceBetweenLabelFramesWithTitleFont:(id)arg1 subtitleFont:(id)arg2 multilineTitle:(BOOL)arg3 ;
+(id)defaultTitleTextStyle;
+(id)defaultSubtitleTextStyle;
+(double)distanceBetweenLabelFrames;
+(double)maxHeight;
-(void)_updateTitleFont;
-(void)_updateSubtitleFont;
-(double)titleHeightForWidth:(double)arg1 ;
-(double)distanceBetweenLabelFrames;
-(double)subtitleMaxWidth;
-(double)subtitleHeightForWidth:(double)arg1 ;
-(void)_notifyDelegateIfHeightChanged;
-(unsigned long long)titleNumberOfLines;
-(id)sizeCacheKeyForLabel:(id)arg1 width:(double)arg2 ;
-(void)_heightWillChange;
-(unsigned long long)subtitleNumberOfLines;
-(void)setSubtitleMaxWidth:(double)arg1 ;
-(void)setTitleNumberOfLines:(unsigned long long)arg1 ;
-(void)setSubtitleNumberOfLines:(unsigned long long)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<MTLabelStackViewDelegate>)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<MTLabelStackViewDelegate>)delegate;
-(NSString *)title;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(UILabel *)titleLabel;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(UIColor *)subtitleTextColor;
-(void)setSubtitleLabel:(UILabel *)arg1 ;
-(UILabel *)subtitleLabel;
-(UIColor *)titleTextColor;
-(void)setTitleTextColor:(UIColor *)arg1 ;
-(double)heightForWidth:(double)arg1 ;
-(void)updateFonts;
-(void)setTitleTextStyle:(NSString *)arg1 ;
-(NSString *)titleTextStyle;
-(NSString *)subtitleTextStyle;
-(void)setSubtitleTextStyle:(NSString *)arg1 ;
-(void)setSubtitleTextColor:(UIColor *)arg1 ;
@end

