/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSMutableSet;

@interface MTLibraryEntityChanges : NSObject <NSCopying> {

	NSString* _entityName;
	NSMutableSet* _insertedUuids;
	NSMutableSet* _deletedUuids;
	NSMutableSet* _updatedUuids;

}

@property (nonatomic,retain) NSMutableSet * insertedUuids;              //@synthesize insertedUuids=_insertedUuids - In the implementation block
@property (nonatomic,retain) NSMutableSet * deletedUuids;               //@synthesize deletedUuids=_deletedUuids - In the implementation block
@property (nonatomic,retain) NSMutableSet * updatedUuids;               //@synthesize updatedUuids=_updatedUuids - In the implementation block
@property (nonatomic,readonly) NSString * entityName;                   //@synthesize entityName=_entityName - In the implementation block
-(NSMutableSet *)insertedUuids;
-(void)setInsertedUuids:(NSMutableSet *)arg1 ;
-(NSMutableSet *)deletedUuids;
-(void)setDeletedUuids:(NSMutableSet *)arg1 ;
-(NSMutableSet *)updatedUuids;
-(void)setUpdatedUuids:(NSMutableSet *)arg1 ;
-(BOOL)hasUpdates;
-(void)combineChanges:(id)arg1 ;
-(void)addUuid:(id)arg1 changeType:(int)arg2 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)hasInserts;
-(id)initWithEntityName:(id)arg1 ;
-(BOOL)hasDeletes;
-(BOOL)hasChanges;
-(NSString *)entityName;
@end

