/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMStoreUtil/IMBaseStoreService.h>

@class NSDictionary;

@interface MTLibraryLinkService : IMBaseStoreService {

	NSDictionary* _requestParams;

}

@property (nonatomic,retain) NSDictionary * requestParams;              //@synthesize requestParams=_requestParams - In the implementation block
-(void)updateAdamIdForPodcast:(id)arg1 withFeedURLs:(id)arg2 ;
-(id)requestWithParams:(id)arg1 callback:(/*^block*/id)arg2 ;
-(id)createURL;
-(id)init;
-(NSDictionary *)requestParams;
-(void)setRequestParams:(NSDictionary *)arg1 ;
@end

