/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MTLockupHeaderTableViewDelegate <UITableViewDelegate>
@required
-(double)navigationBarHeightForTableView:(id)arg1;
-(double)tabBarHeightForTableView:(id)arg1;

@end

