/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTSingleton.h>
#import <Podcasts/MTLibraryChangeNotifier.h>

@class NSObject, NSMutableDictionary, NSString;

@interface MTMediaLibraryUpdater : MTSingleton <MTLibraryChangeNotifier> {

	id _noteObserver;
	BOOL _updateInProgress;
	NSObject* _observerLock;
	NSObject* _updateLock;
	NSMutableDictionary* _episodeCache;

}

@property (nonatomic,retain) NSObject * observerLock;                                      //@synthesize observerLock=_observerLock - In the implementation block
@property (nonatomic,retain) NSObject * updateLock;                                        //@synthesize updateLock=_updateLock - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * episodeCache;                           //@synthesize episodeCache=_episodeCache - In the implementation block
@property (assign,getter=isUpdateInProgress,nonatomic) BOOL updateInProgress;              //@synthesize updateInProgress=_updateInProgress - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)numberFormatter;
-(void)setUpdateInProgress:(BOOL)arg1 ;
-(void)updateMediaLibraryItems:(BOOL)arg1 ;
-(id)_findOrAddPodcastForMediaItem:(id)arg1 updaterCache:(id)arg2 ;
-(void)_addEpisodeInCtx:(id)arg1 mediaItem:(id)arg2 episodeCache:(id)arg3 podcastUuid:(id)arg4 ;
-(void)importPlaylists:(id)arg1 knownPlaylistIds:(id)arg2 mediaLibraryCache:(id)arg3 playlists:(id)arg4 ;
-(unsigned long long)importPlaylist:(id)arg1 intoContext:(id)arg2 mediaLibraryCache:(id)arg3 knownPlaylistIds:(id)arg4 ;
-(void)updateMediaLibraryFromNotification:(id)arg1 ;
-(void)doLibarayUpdateFromNotification;
-(BOOL)haveMediaLibraryPropertiesChangedForEpisode:(id)arg1 ;
-(id)propertiesForMediaLibrary;
-(void)context:(id)arg1 didUpdateObjects:(id)arg2 ;
-(void)startObservingMediaLibrary;
-(void)stopObservingMediaLibrary;
-(void)_printMediaItemPropertiesForItem:(id)arg1 ;
-(NSMutableDictionary *)episodeCache;
-(void)setEpisodeCache:(NSMutableDictionary *)arg1 ;
-(id)init;
-(BOOL)isUpdateInProgress;
-(void)setObserverLock:(NSObject *)arg1 ;
-(NSObject *)observerLock;
-(NSObject *)updateLock;
-(void)setUpdateLock:(NSObject *)arg1 ;
@end

