/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTMigrationAppDelegate_Shared.h>

@class MTAppDelegate_iOS;

@interface MTMigrationAppDelegate_iOS : MTMigrationAppDelegate_Shared {

	MTAppDelegate_iOS* _appDelegate;

}
-(id)appDelegate;
@end

