/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, MPMediaPlaylist, NSString, NSNumber;

@interface MTMLPlaylist : NSObject {

	NSMutableArray* _children;
	BOOL _cachedEmpty;
	BOOL _empty;
	BOOL _isFolder;
	BOOL _isGenius;
	BOOL _isOnTheGo;
	BOOL _isSmart;
	BOOL _isHidden;
	MPMediaPlaylist* _playlist;
	NSString* _name;
	NSNumber* _mediaLibraryId;
	NSNumber* _parentMediaLibraryId;

}

@property (retain) MPMediaPlaylist * playlist;                             //@synthesize playlist=_playlist - In the implementation block
@property (nonatomic,retain) NSString * name;                              //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSNumber * mediaLibraryId;                    //@synthesize mediaLibraryId=_mediaLibraryId - In the implementation block
@property (nonatomic,retain) NSNumber * parentMediaLibraryId;              //@synthesize parentMediaLibraryId=_parentMediaLibraryId - In the implementation block
@property (assign,nonatomic) BOOL isFolder;                                //@synthesize isFolder=_isFolder - In the implementation block
@property (assign,nonatomic) BOOL isGenius;                                //@synthesize isGenius=_isGenius - In the implementation block
@property (assign,nonatomic) BOOL isOnTheGo;                               //@synthesize isOnTheGo=_isOnTheGo - In the implementation block
@property (assign,nonatomic) BOOL isSmart;                                 //@synthesize isSmart=_isSmart - In the implementation block
@property (assign,nonatomic) BOOL isHidden;                                //@synthesize isHidden=_isHidden - In the implementation block
+(id)playlistWithMPPlaylist:(id)arg1 ;
-(NSNumber *)mediaLibraryId;
-(BOOL)isGenius;
-(BOOL)isOnTheGo;
-(void)setMediaLibraryId:(NSNumber *)arg1 ;
-(NSNumber *)parentMediaLibraryId;
-(void)setParentMediaLibraryId:(NSNumber *)arg1 ;
-(BOOL)isSmart;
-(void)setIsFolder:(BOOL)arg1 ;
-(void)setIsGenius:(BOOL)arg1 ;
-(void)setIsOnTheGo:(BOOL)arg1 ;
-(void)setIsSmart:(BOOL)arg1 ;
-(BOOL)isHidden;
-(id)description;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(BOOL)isEmpty;
-(void)setPlaylist:(MPMediaPlaylist *)arg1 ;
-(MPMediaPlaylist *)playlist;
-(id)children;
-(BOOL)isFolder;
-(void)addChild:(id)arg1 ;
-(void)setIsHidden:(BOOL)arg1 ;
@end

