/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MusicTabBarController.h>
#import <Podcasts/MTStoreTabControllerSizeDelegate.h>
#import <Podcasts/MTTabBarLastSelectionProtocol.h>

@class UIViewController, UIButton, NSString;

@interface MTMusicTabController : MusicTabBarController <MTStoreTabControllerSizeDelegate, MTTabBarLastSelectionProtocol> {

	UIViewController* _lastSelectedViewController;
	UIButton* _nowPlayingButton;

}

@property (assign,nonatomic,__weak) UIViewController * lastSelectedViewController;              //@synthesize lastSelectedViewController=_lastSelectedViewController - In the implementation block
@property (nonatomic,retain) UIButton * nowPlayingButton;                                       //@synthesize nowPlayingButton=_nowPlayingButton - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)switchToLastSelectedViewController;
-(void)setLastSelectedViewController:(UIViewController *)arg1 ;
-(UIViewController *)lastSelectedViewController;
-(id)metricsName;
-(id)init;
-(void)traitCollectionDidChange:(id)arg1 ;
-(long long)preferredStatusBarStyle;
-(unsigned long long)supportedInterfaceOrientations;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)setSelectedViewController:(id)arg1 ;
-(UIButton *)nowPlayingButton;
-(void)setNowPlayingButton:(UIButton *)arg1 ;
@end

