/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTSingleton.h>

@protocol OS_dispatch_queue;
@class NSObject;

@interface MTNotificationManager : MTSingleton {

	NSObject*<OS_dispatch_queue> _workQueue;

}
-(BOOL)canSendNewEpisodeAlerts;
-(BOOL)canSendNotification:(unsigned long long)arg1 ;
-(id)computeNotifications;
-(void)markEpisodesAsNotified:(id)arg1 ;
-(void)showPodcastDetailForUUID:(id)arg1 andEpisodeUUIDs:(id)arg2 ;
-(void)scheduleLocationNotificationForPodcast:(id)arg1 ;
-(void)processNotifications;
-(void)handleLocalNotification:(id)arg1 ;
-(void)clearAllNotifications;
-(id)init;
-(void)setupNotifications;
-(void)scheduleLocalNotifications:(id)arg1 ;
@end

