/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary, NSArray;

@interface MTNotificationInfo : NSObject {

	NSMutableDictionary* _podcasts;
	unsigned long long _totalNewEpisodeCount;

}

@property (assign,nonatomic) unsigned long long totalNewEpisodeCount;              //@synthesize totalNewEpisodeCount=_totalNewEpisodeCount - In the implementation block
@property (nonatomic,readonly) NSArray * podcasts; 
-(id)podcastForUuid:(id)arg1 ;
-(NSArray *)podcasts;
-(void)setTotalNewEpisodeCount:(unsigned long long)arg1 ;
-(id)addPodcastWithTitle:(id)arg1 uuid:(id)arg2 ;
-(unsigned long long)totalNewEpisodeCount;
-(void)addPodcast:(id)arg1 ;
-(id)init;
@end

