/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTResultsController.h>

@interface MTNullResultsController : MTResultsController {

	unsigned long long _numberOfObjects;

}

@property (assign,nonatomic) unsigned long long numberOfObjects;              //@synthesize numberOfObjects=_numberOfObjects - In the implementation block
-(unsigned long long)numberOfObjectsInSection:(unsigned long long)arg1 ;
-(id)indexPathForObject:(id)arg1 ;
-(void)setNumberOfObjects:(unsigned long long)arg1 ;
-(id)init;
-(id)objectAtIndex:(unsigned long long)arg1 ;
-(void)reloadData;
-(unsigned long long)indexOfObject:(id)arg1 ;
-(id)allObjects;
-(unsigned long long)numberOfObjects;
-(id)objectAtIndexPath:(id)arg1 ;
@end

