/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTSingleton.h>

@protocol OS_dispatch_queue;
@class NSMutableArray, NSObject;

@interface MTObjectRetainer : MTSingleton {

	NSMutableArray* _objects;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) NSMutableArray * objects;                        //@synthesize objects=_objects - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(void)retainObject:(id)arg1 forDuration:(double)arg2 ;
-(void)releaseObject:(id)arg1 ;
-(void)retainObject:(id)arg1 ;
-(void)releaseObject:(id)arg1 afterDuration:(double)arg2 ;
-(id)init;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSMutableArray *)objects;
-(void)setObjects:(NSMutableArray *)arg1 ;
@end

