/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTBaseProcessor.h>

@interface MTPlaylistQueryManager : MTBaseProcessor
+(id)_allPodcastsInCtx:(id)arg1 ;
+(void)updateEpisodesForSettings:(id)arg1 ctx:(id)arg2 ;
+(void)_fixSortOrder:(id)arg1 generated_p:(BOOL*)arg2 ;
+(void)_sortUngroupedList:(id)arg1 inPlaylist:(id)arg2 ;
+(BOOL)updatePlaylist:(id)arg1 inContext:(id)arg2 ;
-(void)updateAllPlaylistsWithCompletion:(/*^block*/id)arg1 ;
-(void)feedUpdateDidComplete:(id)arg1 ;
-(void)resultsChangedWithDeletedIds:(id)arg1 andInsertIds:(id)arg2 ;
-(void)createDefaultPlaylists;
-(void)updatePlaylistsWithUuids:(id)arg1 ;
-(BOOL)updatePlaylistWithUuid:(id)arg1 inContext:(id)arg2 ;
-(id)init;
-(id)predicate;
-(id)entityName;
@end

