/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTPlayerController.h>
#import <libobjc.A.dylib/AVPictureInPictureControllerDelegate.h>

@class NSString;

@interface MTPlayerController_iOS : MTPlayerController <AVPictureInPictureControllerDelegate>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)setSharedInstance:(id)arg1 ;
-(BOOL)shouldPresentNowPlayingForItem:(id)arg1 presentationType:(unsigned long long)arg2 ;
-(void)currentItemDidChange;
-(void)pictureInPictureControllerFailedToStartPictureInPicture:(id)arg1 withError:(id)arg2 ;
-(id)init;
-(void)pictureInPictureControllerWillStartPictureInPicture:(id)arg1 ;
-(void)pictureInPictureControllerDidStartPictureInPicture:(id)arg1 ;
-(void)pictureInPictureControllerWillStopPictureInPicture:(id)arg1 ;
-(void)pictureInPictureControllerDidStopPictureInPicture:(id)arg1 ;
-(void)pictureInPictureController:(id)arg1 restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:(/*^block*/id)arg2 ;
@end

