/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTBasePlaylistEpisodeListViewController.h>
#import <Podcasts/MTPlaylistLayoutControllerProtocol.h>

@protocol MTPlaylistLayoutViewControllerDelegate;
@class UIButton, UIPopoverController, NSString, UIRefreshControl, UIBarButtonItem, UIView, MTAllPropertyChangesQueryObserver;

@interface MTPlaylistEpisodeListViewController : MTBasePlaylistEpisodeListViewController <MTPlaylistLayoutControllerProtocol> {

	UIButton* _settingsButton;
	UIPopoverController* _episodePopover;
	NSString* _settingsUuidDisplayingPopover;
	UIPopoverController* _settingsPopover;
	UIRefreshControl* _refreshControl;
	UIBarButtonItem* _settingsButtonItem;
	unsigned long long _episodesCount;
	UIView* _footerView;
	MTAllPropertyChangesQueryObserver* _downloadedQuery;
	BOOL _downloadsAvailable;
	BOOL _downloadButtonEnabled;
	/*^block*/id _settingsBlock;
	id<MTPlaylistLayoutViewControllerDelegate> _layoutDelegate;

}

@property (assign,nonatomic) BOOL downloadsAvailable;                                                       //@synthesize downloadsAvailable=_downloadsAvailable - In the implementation block
@property (assign,nonatomic) BOOL downloadButtonEnabled;                                                    //@synthesize downloadButtonEnabled=_downloadButtonEnabled - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) id settingsBlock;                                                                //@synthesize settingsBlock=_settingsBlock - In the implementation block
@property (assign,nonatomic,__weak) id<MTPlaylistLayoutViewControllerDelegate> layoutDelegate;              //@synthesize layoutDelegate=_layoutDelegate - In the implementation block
+(id)stationPodcastPredicateForPlaylist:(id)arg1 ;
-(void)didEndRefreshing;
-(id)previewPlayAction;
-(void)feedUpdateDidComplete:(id)arg1 ;
-(id)leftButtonItems;
-(id)emptyListMessage;
-(id)leftEditingItems;
-(id)toolbarButtonItems;
-(void)downloadAll:(id)arg1 ;
-(void)setDownloadButtonEnabled:(BOOL)arg1 ;
-(void)setDownloadsAvailable:(BOOL)arg1 ;
-(id)settingsButtonItem;
-(void)showSettings:(id)arg1 ;
-(void)_updatePlaylist;
-(void)updateEditingState:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)updateDownloadButtonState;
-(void)playlistSettingsDidChange;
-(id)settingsBlock;
-(void)setSettingsBlock:(id)arg1 ;
-(void)finishedSettings:(id)arg1 ;
-(void)playlistSettingsDidChangeSetting:(id)arg1 ;
-(BOOL)downloadButtonEnabled;
-(BOOL)downloadsAvailable;
-(void)feedUpdateDidStart:(id)arg1 ;
-(id)settingsPopover;
-(void)dealloc;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)beginRefreshing;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)viewDidLoad;
-(id)previewActionItems;
-(id)popoverController;
-(id)footerView;
-(void)setLayoutDelegate:(id<MTPlaylistLayoutViewControllerDelegate>)arg1 ;
-(id<MTPlaylistLayoutViewControllerDelegate>)layoutDelegate;
-(id)settingsButton;
@end

