/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/IMPlayerItem.h>

@class NSString, NSURL, NSDate, MTEpisode;

@interface MTPlayerItem : IMPlayerItem {

	NSString* _podcastUuid;
	NSString* _podcastFeedUrl;
	long long _podcastStoreId;
	NSURL* _artworkUrl;
	NSString* _episodeUuid;
	NSString* _episodeGuid;
	long long _episodeStoreId;
	long long _episodePID;
	NSDate* _pubDate;
	NSString* _subtitle;
	NSString* _itemDescription;
	NSString* _storeReportingParams;

}

@property (nonatomic,retain) NSString * podcastUuid;                       //@synthesize podcastUuid=_podcastUuid - In the implementation block
@property (nonatomic,retain) NSString * podcastFeedUrl;                    //@synthesize podcastFeedUrl=_podcastFeedUrl - In the implementation block
@property (assign,nonatomic) long long podcastStoreId;                     //@synthesize podcastStoreId=_podcastStoreId - In the implementation block
@property (nonatomic,retain) NSURL * artworkUrl;                           //@synthesize artworkUrl=_artworkUrl - In the implementation block
@property (nonatomic,retain) NSString * episodeUuid;                       //@synthesize episodeUuid=_episodeUuid - In the implementation block
@property (nonatomic,retain) NSString * episodeGuid;                       //@synthesize episodeGuid=_episodeGuid - In the implementation block
@property (assign,nonatomic) long long episodeStoreId;                     //@synthesize episodeStoreId=_episodeStoreId - In the implementation block
@property (assign,nonatomic) long long episodePID;                         //@synthesize episodePID=_episodePID - In the implementation block
@property (nonatomic,retain) NSDate * pubDate;                             //@synthesize pubDate=_pubDate - In the implementation block
@property (nonatomic,retain) NSString * subtitle;                          //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,retain) NSString * itemDescription;                   //@synthesize itemDescription=_itemDescription - In the implementation block
@property (nonatomic,readonly) long long mpItemType; 
@property (nonatomic,retain) NSString * storeReportingParams;              //@synthesize storeReportingParams=_storeReportingParams - In the implementation block
@property (nonatomic,readonly) MTEpisode * episode; 
+(id)createAssetForUrl:(id)arg1 ;
+(id)subtitleStringForArtist:(id)arg1 album:(id)arg2 ;
+(id)subtitleStringForEpisode:(id)arg1 ;
-(NSString *)episodeUuid;
-(MTEpisode *)episode;
-(NSString *)podcastUuid;
-(void)setPodcastUuid:(NSString *)arg1 ;
-(NSURL *)artworkUrl;
-(long long)episodeStoreId;
-(long long)episodePID;
-(id)externalMetadata;
-(NSString *)episodeGuid;
-(NSString *)podcastFeedUrl;
-(void)notifyUserIsNotPlayable;
-(long long)mpItemType;
-(void)retrieveArtwork:(/*^block*/id)arg1 withSize:(CGSize)arg2 ;
-(void)setPodcastFeedUrl:(NSString *)arg1 ;
-(long long)podcastStoreId;
-(void)setPodcastStoreId:(long long)arg1 ;
-(void)setArtworkUrl:(NSURL *)arg1 ;
-(void)setEpisodeUuid:(NSString *)arg1 ;
-(void)setEpisodeGuid:(NSString *)arg1 ;
-(void)setEpisodeStoreId:(long long)arg1 ;
-(void)setEpisodePID:(long long)arg1 ;
-(NSString *)storeReportingParams;
-(void)setStoreReportingParams:(NSString *)arg1 ;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(id)initWithAsset:(id)arg1 ;
-(id)nowPlayingInfo;
-(void)updateActivity:(id)arg1 ;
-(NSString *)itemDescription;
-(BOOL)isPlayable;
-(NSDate *)pubDate;
-(void)setPubDate:(NSDate *)arg1 ;
-(void)setItemDescription:(NSString *)arg1 ;
@end

