/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTPredicateManifest.h>

@class NSString;

@interface MTPodcastManifest : MTPredicateManifest {

	NSString* _podcastUuid;
	unsigned long long _sectionType;

}

@property (nonatomic,retain) NSString * podcastUuid;                      //@synthesize podcastUuid=_podcastUuid - In the implementation block
@property (assign,nonatomic) unsigned long long sectionType;              //@synthesize sectionType=_sectionType - In the implementation block
+(id)createManifestForActivity:(id)arg1 ;
+(id)activityTypeSuffix;
-(NSString *)podcastUuid;
-(void)setPodcastUuid:(NSString *)arg1 ;
-(id)initWithInitialEpisodeUuid:(id)arg1 sectionType:(unsigned long long)arg2 ;
-(void)_propertyDidChange;
-(id)activity;
-(unsigned long long)sectionType;
-(void)setSectionType:(unsigned long long)arg1 ;
@end

