/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>
#import <IMStoreUtil/IMMetricsDataSource.h>

@class NSString, NSOrderedSet, MTPlaylist, MTPodcast;

@interface MTPodcastPlaylistSettings : NSManagedObject <IMMetricsDataSource>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) int downloaded; 
@property (assign,nonatomic) long long episodesToShow; 
@property (assign,nonatomic) long long flags; 
@property (assign,nonatomic) long long mediaType; 
@property (assign,nonatomic) BOOL showPlayedEpisodes; 
@property (assign,nonatomic) long long sortOrder; 
@property (nonatomic,retain) NSString * uuid; 
@property (assign,nonatomic) BOOL visible; 
@property (nonatomic,retain) NSOrderedSet * episodes; 
@property (nonatomic,retain) MTPlaylist * playlist; 
@property (nonatomic,retain) MTPlaylist * playlistIfDefault; 
@property (nonatomic,retain) MTPodcast * podcast; 
@property (assign,nonatomic) long long playOrder; 
+(id)insertNewSettingsInManagedObjectContext:(id)arg1 ;
+(id)stringForEpisodes:(long long)arg1 short:(BOOL)arg2 defaultValue:(long long)arg3 ;
+(id)stringForMedia:(int)arg1 short:(BOOL)arg2 ;
+(id)episodesOptionArray:(BOOL)arg1 defaultValue:(long long)arg2 ;
+(id)episodesOptionValues;
+(id)mediaOptionArray:(BOOL)arg1 ;
+(id)mediaOptionValues;
-(double)oldestEpisodeDate;
-(void)setTracksDefault:(BOOL)arg1 ;
-(id)metricsKeys;
-(double)latestEpisodeDate;
-(id)predicateForSettings;
-(long long)integerForEpisodesToShow;
-(BOOL)tracksDefault;
-(void)takeValuesFromDefaultSettings:(id)arg1 ;
-(id)metricsContentIdentifier;
-(id)metricsAdditionalData;
-(BOOL)needsUpdate;
-(void)setNeedsUpdate:(BOOL)arg1 ;
@end

