/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSString, MTPodcastHeaderView, UIViewController;

@interface MTPodcastHeaderContainerViewController : UIViewController {

	NSString* _podcastUuid;
	MTPodcastHeaderView* _headerView;
	UIViewController* _childViewController;

}

@property (nonatomic,retain) UIViewController * childViewController;              //@synthesize childViewController=_childViewController - In the implementation block
-(id)initWithPodcastUuid:(id)arg1 ;
-(BOOL)metricsEnabled;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(UIViewController *)childViewController;
-(void)setChildViewController:(UIViewController *)arg1 ;
@end

