/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTAllPropertyChangesQueryObserver.h>

@class NSArray;

@interface MTPropertyChangeQueryObserver : MTAllPropertyChangesQueryObserver

@property (nonatomic,retain) NSArray * propertyKeys; 
+(Class)fetchedResultsControllerClass;
-(id)_frc;
-(NSArray *)propertyKeys;
-(void)setPropertyKeys:(NSArray *)arg1 ;
@end

