/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Podcasts/Podcasts-Structs.h>
@interface MTRadioGroupDescription : NSObject {

	CFArrayRef _radioSettings;
	unsigned long long _value;
	/*^block*/id _changeHandler;

}

@property (nonatomic,retain) CFArrayRef radioSettings;              //@synthesize radioSettings=_radioSettings - In the implementation block
@property (assign,nonatomic) unsigned long long value;              //@synthesize value=_value - In the implementation block
@property (nonatomic,copy) id changeHandler;                        //@synthesize changeHandler=_changeHandler - In the implementation block
+(id)radioGroupWithInitialValue:(unsigned long long)arg1 changeHandler:(/*^block*/id)arg2 ;
-(void)addRadioSetting:(id)arg1 ;
-(CFArrayRef)radioSettings;
-(void)setRadioSettings:(CFArrayRef)arg1 ;
-(id)init;
-(id)settings;
-(unsigned long long)value;
-(void)setValue:(unsigned long long)arg1 ;
-(void)setChangeHandler:(id)arg1 ;
-(id)changeHandler;
@end

