/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTItemListManifest.h>

@class NSArray;

@interface MTStoreManifest : MTItemListManifest {

	NSArray* _adamIds;

}

@property (nonatomic,retain) NSArray * adamIds;              //@synthesize adamIds=_adamIds - In the implementation block
+(id)storeMediaDictionariesToPlayerItems:(id)arg1 ;
+(id)_storeMediaPlayerItemsToPlayerItems:(id)arg1 ;
+(id)createManifestForActivity:(id)arg1 ;
+(id)activityTypeSuffix;
-(id)initWithStoreMediaDictionaries:(id)arg1 initialIndex:(unsigned long long)arg2 ;
-(id)initWithStoreMediaPlayerItems:(id)arg1 initialIndex:(unsigned long long)arg2 ;
-(void)setAdamIds:(NSArray *)arg1 ;
-(void)_loadItemsWithInitialIndex:(unsigned long long)arg1 ;
-(id)initWithItems:(id)arg1 initialIndex:(unsigned long long)arg2 ;
-(NSArray *)adamIds;
-(id)initWithAdamIds:(id)arg1 initialIndex:(unsigned long long)arg2 ;
-(id)activity;
@end

