/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTBasePodcastListViewController.h>
#import <Podcasts/MTStationCellDelegate.h>
#import <Podcasts/MTSourceListDelegate.h>
#import <UIKit/UIViewControllerRestoration.h>

@class MTPlaylistSelectPodcastListViewController, NSString;

@interface MTStationsViewController : MTBasePodcastListViewController <MTStationCellDelegate, MTSourceListDelegate, UIViewControllerRestoration> {

	MTPlaylistSelectPodcastListViewController* _newPlaylistController;
	BOOL _folder;

}

@property (assign,getter=isFolder,nonatomic) BOOL folder;              //@synthesize folder=_folder - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)viewControllerWithRestorationIdentifierPath:(id)arg1 coder:(id)arg2 ;
+(id)defaultsKey;
-(void)sourceList:(id)arg1 didSelectItemUuid:(id)arg2 atIndexPath:(id)arg3 ;
-(void)sourceList:(id)arg1 didUpdateSelectedItemUuid:(id)arg2 ;
-(void)restoreSelection;
-(id)attributedTitleForRefreshControl;
-(void)getObjectId:(id*)arg1 andIndexPath:(id*)arg2 forItemWithUuid:(id)arg3 ;
-(id)firstValidIndexPath;
-(id)newCellInstanceWithReuseIdentifier:(id)arg1 ;
-(void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3 ;
-(void)feedUpdateDidComplete:(id)arg1 ;
-(void)feedUpdateDidStart;
-(BOOL)showsNewStation;
-(long long)_minEditableRow;
-(id)makeNewStationAlertView;
-(id)defaultSystemTintColor;
-(void)createPlaylistWithName:(id)arg1 includesAll:(BOOL)arg2 podcasts:(id)arg3 ;
-(void)cancelNewPlaylist:(id)arg1 ;
-(void)doneNewPlaylist:(id)arg1 ;
-(void)playPlaylist:(id)arg1 selectCell:(BOOL)arg2 ;
-(void)stationCellDidTapPlayButton:(id)arg1 ;
-(void)finishedEditing:(id)arg1 ;
-(id)makeNewStationAlertController;
-(id)metricsName;
-(void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5 ;
-(void)controllerDidChangeContent:(id)arg1 ;
-(void)dealloc;
-(void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2 ;
-(void)encodeRestorableStateWithCoder:(id)arg1 ;
-(void)decodeRestorableStateWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)viewDidLoad;
-(void)refresh:(id)arg1 ;
-(void)addStation:(id)arg1 ;
-(void)updateEditButton;
-(id)reuseIdentifierForRow:(id)arg1 ;
-(BOOL)isFolder;
-(void)setFolder:(BOOL)arg1 ;
-(void)setRefreshing:(BOOL)arg1 ;
@end

