/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MTStorePlatformUtil : NSObject
+(id)storeMediaDictionaryFromStorePlatformDictionary:(id)arg1 artworkSize:(double)arg2 ;
+(id)pubDateFromStoreMediaDictionary:(id)arg1 ;
+(id)latestEpisodeDictionaryFromPodcastDictionary:(id)arg1 ;
+(void)loadTopPodcastsChartsWithCompletionHandler:(/*^block*/id)arg1 withLimit:(unsigned long long)arg2 ;
+(id)storeMediaDictionaryFromStorePlatformDictionary:(id)arg1 artworkSize:(double)arg2 restricted:(BOOL*)arg3 ;
+(BOOL)isExplicitForStorePlatformDictionary:(id)arg1 ;
+(id)stringFromDictionary:(id)arg1 forKey:(id)arg2 ;
+(id)artworkDictionary:(id)arg1 closestToSize:(double)arg2 ;
+(BOOL)isAValue:(id)arg1 ;
+(id)encodedQueryStringFromDictionary:(id)arg1 ;
+(id)dateFromFormattedString:(id)arg1 ;
+(id)formatDate:(id)arg1 ;
@end

