/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MTTableViewCell.h>

@class UISwitch;

@interface MTSwitchCell : MTTableViewCell {

	/*^block*/id _toggleChanged;
	UISwitch* _toggle;

}

@property (nonatomic,retain) UISwitch * toggle;              //@synthesize toggle=_toggle - In the implementation block
@property (nonatomic,copy) id toggleChanged;                 //@synthesize toggleChanged=_toggleChanged - In the implementation block
+(id)titleFont;
-(void)setupCell;
-(void)toggleChanged:(id)arg1 ;
-(void)toggleOn:(BOOL)arg1 ;
-(id)toggleChanged;
-(void)setToggleChanged:(id)arg1 ;
-(void)setEnabled:(BOOL)arg1 ;
-(UISwitch *)toggle;
-(void)setToggle:(UISwitch *)arg1 ;
@end

