/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, UIColor;

@interface MTTheme : NSManagedObject

@property (nonatomic,retain) NSString * uuid; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) UIColor * primaryTextColor; 
@property (nonatomic,retain) UIColor * secondaryTextColor; 
@property (assign,nonatomic) BOOL isBackgroundLight; 
+(id)insertNewTheme:(id)arg1 forUuid:(id)arg2 inMOC:(id)arg3 ;
+(BOOL)createOrUpdateTheme:(id)arg1 forUuid:(id)arg2 inMOC:(id)arg3 ;
-(id)convertToColorTheme;
-(void)populateWithColorTheme:(id)arg1 ;
@end

