/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MZUniversalPlaybackPositionMediaItem.h>

@class NSDictionary, MTEpisode, NSString;

@interface MTUniversalPlaybackPositionMediaItem : NSObject <MZUniversalPlaybackPositionMediaItem> {

	NSDictionary* _mediaItemDictionary;
	MTEpisode* _episode;

}

@property (nonatomic,retain) NSDictionary * mediaItemDictionary;              //@synthesize mediaItemDictionary=_mediaItemDictionary - In the implementation block
@property (nonatomic,retain) MTEpisode * episode;                             //@synthesize episode=_episode - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(MTEpisode *)episode;
-(void)setEpisode:(MTEpisode *)arg1 ;
-(void)populateEpisodeDictionary;
-(NSDictionary *)mediaItemDictionary;
-(void)setMediaItemDictionary:(NSDictionary *)arg1 ;
-(NSString *)description;
-(void)enumerateValuesForProperties:(id)arg1 usingBlock:(/*^block*/id)arg2 ;
@end

