/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:21 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <MPUFoundation/MPUPercentDrivenInteractionTransition.h>

@protocol UIViewControllerContextTransitioning;
@class MusicNowPlayingTransitionController, UIPanGestureRecognizer, MusicNowPlayingPresentationController;

@interface MusicNowPlayingInteractionController : MPUPercentDrivenInteractionTransition {

	CGPoint _initialLocation;
	id<UIViewControllerContextTransitioning> _context;
	BOOL _transitionStarted;
	BOOL _transitionFinished;
	BOOL _transitionCanceled;
	BOOL _isRubberbanding;
	MusicNowPlayingTransitionController* _animationController;
	UIPanGestureRecognizer* _gestureRecognizer;
	MusicNowPlayingPresentationController* _presentationController;

}

@property (nonatomic,retain) MusicNowPlayingTransitionController * animationController;                   //@synthesize animationController=_animationController - In the implementation block
@property (nonatomic,retain) UIPanGestureRecognizer * gestureRecognizer;                                  //@synthesize gestureRecognizer=_gestureRecognizer - In the implementation block
@property (nonatomic,retain) MusicNowPlayingPresentationController * presentationController;              //@synthesize presentationController=_presentationController - In the implementation block
-(void)_panRecognized:(id)arg1 ;
-(void)setPresentationController:(MusicNowPlayingPresentationController *)arg1 ;
-(void)dealloc;
-(void)cancelInteractiveTransition;
-(void)setAnimationController:(MusicNowPlayingTransitionController *)arg1 ;
-(void)setGestureRecognizer:(UIPanGestureRecognizer *)arg1 ;
-(UIPanGestureRecognizer *)gestureRecognizer;
-(void)finishInteractiveTransition;
-(void)startInteractiveTransition:(id)arg1 ;
-(MusicNowPlayingTransitionController *)animationController;
-(void)updateInteractiveTransition:(double)arg1 ;
-(MusicNowPlayingPresentationController *)presentationController;
-(void)stopInteractiveTransition;
@end

