/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ITMLKit/IKJSObject.h>
#import <Podcasts/MusicJSNowPlayingController.h>

@protocol MusicJSNowPlayingController <JSExport>
@required
-(void)presentNowPlayingView;

@end


@protocol MTAppController;
@class IMAVPlayer;

@interface MusicJSNowPlayingController : IKJSObject <MusicJSNowPlayingController> {

	IMAVPlayer* _player;
	id<MTAppController> _appController;

}

@property (nonatomic,retain) IMAVPlayer * player;                            //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) id<MTAppController> appController;              //@synthesize appController=_appController - In the implementation block
-(void)presentNowPlayingView;
-(IMAVPlayer *)player;
-(void)setPlayer:(IMAVPlayer *)arg1 ;
-(id<MTAppController>)appController;
-(void)setAppController:(id<MTAppController>)arg1 ;
@end

