/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/MusicPlaybackProgressScrubberDelegate.h>

@protocol MusicPlaybackProgressScrubbing, MusicPlaybackProgressScrubberDelegate;
@class IMPlayerItem, IMAVPlayer, NSString;

@interface MusicPlaybackProgressScrubberController : NSObject <MusicPlaybackProgressScrubberDelegate> {

	IMPlayerItem* _currentItem;
	float _currentRate;
	double _lastSeekedTime;
	id _periodicTimeObserver;
	long long _scrubbingTransactionCount;
	IMAVPlayer* _player;
	id<MusicPlaybackProgressScrubbing> _playbackProgressScrubber;
	id<MusicPlaybackProgressScrubberDelegate> _playbackProgressScrubberDelegate;

}

@property (nonatomic,retain) IMAVPlayer * player;                                                                            //@synthesize player=_player - In the implementation block
@property (assign,nonatomic,__weak) id<MusicPlaybackProgressScrubbing> playbackProgressScrubber;                             //@synthesize playbackProgressScrubber=_playbackProgressScrubber - In the implementation block
@property (assign,nonatomic,__weak) id<MusicPlaybackProgressScrubberDelegate> playbackProgressScrubberDelegate;              //@synthesize playbackProgressScrubberDelegate=_playbackProgressScrubberDelegate - In the implementation block
@property (nonatomic,readonly) NSString * localizedScrubSpeedText; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setPlaybackProgressScrubber:(id<MusicPlaybackProgressScrubbing>)arg1 ;
-(void)_destroyPeriodicTimeObserverIfNeeded;
-(void)_endScrubbingTransactionForFinalCleanup:(BOOL)arg1 ;
-(id<MusicPlaybackProgressScrubbing>)playbackProgressScrubber;
-(void)_currentItemLoadedDurationDidChange;
-(void)_setCurrentItem:(id)arg1 force:(BOOL)arg2 ;
-(void)_updateTimeValuesUsingItemTime:(BOOL)arg1 force:(BOOL)arg2 ;
-(void)_beginScrubbingTransaction;
-(void)playbackProgressScrubberTrackingDidBegin:(id)arg1 ;
-(void)playbackProgressScrubberTrackingDidEnd:(id)arg1 ;
-(void)playbackProgressScrubber:(id)arg1 didChangeCurrentTime:(double)arg2 ;
-(void)playbackProgressScrubber:(id)arg1 didChangeScrubSpeed:(long long)arg2 ;
-(void)_updateDurationForCurrentItem;
-(void)_setCurrentTimeIfPossible:(double)arg1 ;
-(void)_createPeriodicTimeObserverIfNeeded;
-(id)initWithPlayer:(id)arg1 playbackProgressScrubber:(id)arg2 ;
-(id<MusicPlaybackProgressScrubberDelegate>)playbackProgressScrubberDelegate;
-(void)setPlaybackProgressScrubberDelegate:(id<MusicPlaybackProgressScrubberDelegate>)arg1 ;
-(void)dealloc;
-(NSString *)localizedScrubSpeedText;
-(void)_playerItemDidChangeNotification:(id)arg1 ;
-(void)_playerRateDidChangeNotification:(id)arg1 ;
-(void)_currentItemDurationAvailableNotification:(id)arg1 ;
-(IMAVPlayer *)player;
-(void)setPlayer:(IMAVPlayer *)arg1 ;
@end

