/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Podcasts/Podcasts-Structs.h>
#import <Podcasts/MTStoreTabBarController.h>

@class IMAVPlayer, MusicMiniPlayerViewController, MusicNowPlayingViewController;

@interface MusicTabBarController : MTStoreTabBarController {

	BOOL _isMiniPlayerPresented;
	BOOL _shouldIgnorePresentations;
	/*^block*/id _nowPlayingPresentationCompletionHandler;
	BOOL _miniPlayerVisible;
	IMAVPlayer* _player;
	MusicMiniPlayerViewController* _miniPlayerViewController;
	MusicNowPlayingViewController* _nowPlayingViewController;

}

@property (assign,getter=isMiniPlayerVisible,nonatomic) BOOL miniPlayerVisible;                       //@synthesize miniPlayerVisible=_miniPlayerVisible - In the implementation block
@property (nonatomic,retain) IMAVPlayer * player;                                                     //@synthesize player=_player - In the implementation block
@property (nonatomic,readonly) MusicMiniPlayerViewController * miniPlayerViewController;              //@synthesize miniPlayerViewController=_miniPlayerViewController - In the implementation block
@property (nonatomic,readonly) MusicNowPlayingViewController * nowPlayingViewController;              //@synthesize nowPlayingViewController=_nowPlayingViewController - In the implementation block
-(MusicMiniPlayerViewController *)miniPlayerViewController;
-(MusicNowPlayingViewController *)nowPlayingViewController;
-(void)presentNowPlayingViewControllerWithCompletion:(/*^block*/id)arg1 ;
-(void)_dismissNowPlaying:(id)arg1 ;
-(void)presentMiniPlayerViewController;
-(void)dismissMiniPlayerViewController;
-(void)_playerContentsChangedNotification:(id)arg1 ;
-(void)_updateMiniPlayerVisiblity;
-(void)presentNowPlayingViewController;
-(void)setMiniPlayerVisible:(BOOL)arg1 ;
-(BOOL)isMiniPlayerVisible;
-(void)dismissNowPlayingViewController;
-(void)dealloc;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)setTransientViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setClientContext:(id)arg1 ;
-(IMAVPlayer *)player;
-(void)setPlayer:(IMAVPlayer *)arg1 ;
-(void)_playerDidReloadWithPlaybackContextNotification:(id)arg1 ;
@end

