/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MusicPlaybackProgressScrubbing <NSObject>
@property (assign,getter=isAlwaysLive,nonatomic) BOOL alwaysLive; 
@property (nonatomic,readonly) long long currentScrubSpeed; 
@property (assign,nonatomic,__weak) id<MusicPlaybackProgressScrubberDelegate> scrubberDelegate; 
@property (nonatomic,readonly) double effectiveCurrentTime; 
@property (assign,nonatomic) float rate; 
@property (assign,getter=isScrubbingEnabled,nonatomic) BOOL scrubbingEnabled; 
@property (assign,nonatomic) double totalDuration; 
@property (assign,nonatomic) double loadedDuration; 
@required
-(double)loadedDuration;
-(void)setLoadedDuration:(double)arg1;
-(void)cancelScrubbing;
-(double)effectiveCurrentTime;
-(BOOL)isScrubbingEnabled;
-(void)setRate:(float)arg1;
-(float)rate;
-(long long)currentScrubSpeed;
-(BOOL)isAlwaysLive;
-(void)setCurrentTime:(double)arg1;
-(id<MusicPlaybackProgressScrubberDelegate>)scrubberDelegate;
-(void)setScrubberDelegate:(id)arg1;
-(void)setAlwaysLive:(BOOL)arg1;
-(void)setTotalDuration:(double)arg1;
-(void)setScrubbingEnabled:(BOOL)arg1;
-(double)totalDuration;

@end

