/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, April 18, 2017 at 7:56:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Podcasts.app/Podcasts
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MZKeyValueStoreOperationDelegate <ISStoreURLOperationDelegate,NSObject>
@required
-(void)keyValueStoreOperation:(id)arg1 scheduleURLOperation:(id)arg2;
-(void)keyValueStoreOperationOperationDidFinish:(id)arg1;

@end

