/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:17:59 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSMutableArray;

@interface _SKUIInspectablePropertySection : NSObject {

	NSString* _friendlyName;
	NSMutableArray* _properties;

}

@property (nonatomic,copy) NSString * friendlyName;                      //@synthesize friendlyName=_friendlyName - In the implementation block
@property (nonatomic,readonly) NSMutableArray * properties;              //@synthesize properties=_properties - In the implementation block
-(id)init;
-(NSMutableArray *)properties;
-(void)setFriendlyName:(NSString *)arg1 ;
-(NSString *)friendlyName;
@end

