/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:17:53 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _SKUIResourceCacheValue : NSObject {

	id _resource;
	id _requestCacheKey;

}

@property (nonatomic,readonly) id resource;                     //@synthesize resource=_resource - In the implementation block
@property (nonatomic,readonly) id requestCacheKey;              //@synthesize requestCacheKey=_requestCacheKey - In the implementation block
-(id)resource;
-(id)initWithResource:(id)arg1 requestCacheKey:(id)arg2 ;
-(id)requestCacheKey;
@end

