/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:06 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IKAppScriptFallbackHandler <NSObject>
@required
-(BOOL)canFallbackForError:(id)arg1;
-(id)retrieveScript:(id*)arg1;
-(void)scriptEvaluated:(id)arg1;

@end

