/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:06 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIColor;

@interface SKUIItemOfferButtonAppearance : NSObject {

	UIColor* _buttonColor;
	UIColor* _confirmationColor;

}

@property (nonatomic,readonly) UIColor * buttonColor;                    //@synthesize buttonColor=_buttonColor - In the implementation block
@property (nonatomic,readonly) UIColor * confirmationColor;              //@synthesize confirmationColor=_confirmationColor - In the implementation block
-(id)initWithColorScheme:(id)arg1 ;
-(UIColor *)confirmationColor;
-(UIColor *)buttonColor;
@end

