/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:03 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUICardLayout.h>

@interface SKUIDefaultCardLayout : SKUICardLayout
-(id)attributedStringForButton:(id)arg1 ;
-(id)attributedStringForLabel:(id)arg1 ;
-(double)topInsetForViewElement:(id)arg1 previousViewElement:(id)arg2 width:(double)arg3 ;
@end

