/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:17:57 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUISettingsGroupControllerDelegate <NSObject>
@required
-(id)owningViewControllerForSettingsGroupController:(id)arg1;
-(void)settingsGroupController:(id)arg1 reloadSettingDescription:(id)arg2;
-(id)settingsGroupController:(id)arg1 viewForSettingDescription:(id)arg2;

@end

