/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:01 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UICollectionViewLayoutInvalidationContext.h>

@interface SKUIZoomingShelfCollectionViewLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext {

	BOOL _invalidateGeometryOnlyOfExistingLayoutAttributes;

}

@property (assign,nonatomic) BOOL invalidateGeometryOnlyOfExistingLayoutAttributes;              //@synthesize invalidateGeometryOnlyOfExistingLayoutAttributes=_invalidateGeometryOnlyOfExistingLayoutAttributes - In the implementation block
-(void)setInvalidateGeometryOnlyOfExistingLayoutAttributes:(BOOL)arg1 ;
-(BOOL)invalidateGeometryOnlyOfExistingLayoutAttributes;
@end

