/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:06 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSObject;

@interface SKUIWeakReference : NSObject {

	NSObject* _object;

}

@property (assign,nonatomic,__weak) NSObject * object;              //@synthesize object=_object - In the implementation block
-(NSObject *)object;
-(void)setObject:(NSObject *)arg1 ;
@end

