/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:01 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreServices/SSVURLDataConsumer.h>

@interface SKUICompletionDataConsumer : SSVURLDataConsumer
-(id)objectForData:(id)arg1 response:(id)arg2 error:(id*)arg3 ;
-(id)_invalidResponseError;
@end

