/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:01 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SKUITrendingSearchPageViewDelegate <NSObject>
@optional
-(id)URLForTrendingSearchPageView:(id)arg1;

@required
-(void)trendingSearchPageView:(id)arg1 didSelectSearch:(id)arg2;

@end

