/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:05 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SKUISettingsFamilyViewStateCoordinator : NSObject {

	/*^block*/id _completionBlock;

}
-(void)checkSettingsFamilyViewStateWithBlock:(/*^block*/id)arg1 ;
-(void)_getSubscriptionStatus;
-(void)_returnFamilyViewState:(long long)arg1 ;
-(void)_checkSubscriptionStatus:(id)arg1 isFinal:(BOOL)arg2 error:(id)arg3 ;
@end

