/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:17:57 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <StoreKitUI/SKUIViewElement.h>

@class SKUIButtonViewElement, NSArray;

@interface SKUIHeaderViewElement : SKUIViewElement

@property (nonatomic,readonly) SKUIButtonViewElement * button; 
@property (nonatomic,readonly) NSArray * titleLabels; 
-(SKUIButtonViewElement *)button;
-(id)initWithDOMElement:(id)arg1 parent:(id)arg2 elementFactory:(id)arg3 ;
-(long long)pageComponentType;
-(NSArray *)titleLabels;
@end

