/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:18:05 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SKUITrendingSearch : NSObject {

	NSString* _term;
	NSString* _URLString;

}

@property (nonatomic,retain) NSString * term;                   //@synthesize term=_term - In the implementation block
@property (nonatomic,retain) NSString * URLString;              //@synthesize URLString=_URLString - In the implementation block
-(NSString *)term;
-(NSString *)URLString;
-(void)setTerm:(NSString *)arg1 ;
-(void)setURLString:(NSString *)arg1 ;
@end

