/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:17:55 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/StoreKitUI.framework/StoreKitUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIKeyInput <UITextInputTraits>
@property (nonatomic,readonly) BOOL hasText; 
@required
-(void)insertText:(id)arg1;
-(void)deleteBackward;
-(BOOL)hasText;

@end

