/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 7, 2017 at 4:52:20 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ChatKit/CKBrowserCell.h>

@class UIImageView;

@interface CKBrowserDummyCell : CKBrowserCell {

	UIImageView* _image;

}

@property (nonatomic,retain) UIImageView * image;              //@synthesize image=_image - In the implementation block
+(id)reuseIdentifier;
-(void)layoutSubviews;
-(void)setImage:(UIImageView *)arg1 ;
-(UIImageView *)image;
-(id)iconView;
@end

