/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 7, 2017 at 4:52:19 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CKRecentsManager : NSObject
+(void)loadRecentHandwritings:(/*^block*/id)arg1 ;
+(void)loadRecentStickers:(/*^block*/id)arg1 ;
+(void)loadRecentHandwritingsAndStickers:(/*^block*/id)arg1 ;
@end

