/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 7, 2017 at 4:52:20 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface CKSnapshotUtilities : NSObject
+(id)snapshotForGUID:(id)arg1 ;
+(void)_saveSnapshot:(id)arg1 url:(id)arg2 ;
+(id)_snapshotAtURL:(id)arg1 ;
+(void)cacheSnapshot:(id)arg1 guid:(id)arg2 ;
@end

