/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 7, 2017 at 4:52:20 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIImageView.h>

@class NSArray;

@interface CKStackedAvatarView : UIImageView {

	NSArray* _contacts;

}

@property (nonatomic,copy,readonly) NSArray * contacts;              //@synthesize contacts=_contacts - In the implementation block
-(id)_stackWithMonograms:(id)arg1 ;
-(id)initWithContacts:(id)arg1 ;
-(NSArray *)contacts;
@end

