/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:38 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBSteppedAnimationTimingFunctionCalculator.h>

@interface _SBMinusPageStepper : SBSteppedAnimationTimingFunctionCalculator

@property (nonatomic,readonly) double backgroundBlurAlpha; 
@property (nonatomic,readonly) double pageControlAlpha; 
@property (nonatomic,readonly) double iconsAlpha; 
@property (nonatomic,readonly) double searchViewAlpha; 
-(double)backgroundBlurAlpha;
-(double)pageControlAlpha;
-(double)searchViewAlpha;
-(double)iconsAlpha;
-(id)init;
@end

