/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:38 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol PGPictureInPictureControllerDelegate <NSObject>
@optional
-(void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2;
-(void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2;

@end

