/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:36 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBDashBoardBackgroundStyleTransitioning <NSObject>
@property (assign,nonatomic) long long backgroundStyle; 
@property (getter=isTransitioningBackgroundStyle,nonatomic,readonly) BOOL transitioningBackgroundStyle; 
@required
-(void)beginTransitionToBackgroundStyle:(long long)arg1;
-(void)updateBackgroundStyleTransitionProgress:(double)arg1;
-(BOOL)isTransitioningBackgroundStyle;
-(void)completeTransitionToBackgroundStyle:(long long)arg1;
-(long long)backgroundStyle;
-(void)setBackgroundStyle:(long long)arg1;

@end

