/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:36 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBFAuthenticationResponder <NSObject>
@required
-(void)handleSuccessfulAuthenticationRequest:(id)arg1;
-(void)handleFailedAuthenticationRequest:(id)arg1 error:(id)arg2;
-(void)handleInvalidAuthenticationRequest:(id)arg1;

@end

