/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:36 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <UIKit/UIView.h>

@class SBIcon, SBIconViewMap, SBIconView;

@interface SBIconOverlayDarkeningView : UIView {

	SBIcon* _icon;
	SBIconViewMap* _iconViewMap;
	SBIconView* _iconView;

}
-(id)initWithFrame:(CGRect)arg1 icon:(id)arg2 viewMap:(id)arg3 ;
-(void)layoutSubviews;
@end

