/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:37 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SpringBoard-Structs.h>
#import <SpringBoard/SBLockScreenNotificationCell.h>

@interface SBLockScreenBulletinCell : SBLockScreenNotificationCell
+(double)paddingBetweenTitleAndRelevanceDate;
+(double)rowHeightForTitle:(id)arg1 subtitle:(id)arg2 body:(id)arg3 maxLines:(unsigned long long)arg4 attachmentSize:(CGSize)arg5 secondaryContentSize:(CGSize)arg6 datesVisible:(BOOL)arg7 rowWidth:(double)arg8 includeUnlockActionText:(BOOL)arg9 ;
@end

