/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:20:36 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoard/SBIconListPageControl.h>

@interface SBStarkIconListPageControl : SBIconListPageControl {

	double _scale;

}

@property (assign,nonatomic) double scale;              //@synthesize scale=_scale - In the implementation block
-(id)_iconListIndicatorImage:(BOOL)arg1 ;
-(void)setScale:(double)arg1 ;
-(double)scale;
-(double)_indicatorSpacing;
@end

