/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIView.h>

@class NSString;

@interface _TtCVV5Music4Text7Drawing4View : UIView {

	 _textDrawingContext;

}

@property (readonly,nonatomic) NSString * text; 
@property (readonly,nonatomic) double firstBaselineOffsetFromTop; 
@property (readonly,nonatomic) double lastBaselineOffsetFromBottom; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)text;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(double)lastBaselineOffsetFromBottom;
-(double)firstBaselineOffsetFromTop;
@end

