/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCV5Music7Artwork9Component : _UKNOWN_SUPERCLASS_ {

	 cachingContext;
	 cachingIdentifier;
	 _backgroundColor;
	 imageBackgroundColor;
	 isHighlighted;
	 catalog;
	 idealSize;
	 imageView;
	 imageViewContentMode;
	 placeholder;
	 prefersAutomaticHighlightTreatment;
	 treatment;
	 currentTreatment;
	 borderColor;
	 explicitBackgroundColor;
	 requiresContentsAndLayoutUpdateHandler;
	 imageDidChangeHandler;
	 _treatmentOverlayView;
	 foregroundOverlayColor;
	 isBackgroundColorConfigured;
	 isConfigurationBlockEnabled;
	 didUpdateWithImageFromConfigurationBlock;
	 hasActualImage;
	 isBestImageRepresentation;
	 isApplyingArtworkCatalogDestination;
	 hasClearSinglePointImage;
	 lastProposedAspectRatio;
	 foregroundOverlayView;

}
@end

