/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class _UIFeedbackRetargetBehavior;

@interface IndexBarSelectionManager : NSObject {

	_UIFeedbackRetargetBehavior* _retargetFeedbackBehavior;

}

@property (nonatomic,retain) _UIFeedbackRetargetBehavior * retargetFeedbackBehavior;              //@synthesize retargetFeedbackBehavior=_retargetFeedbackBehavior - In the implementation block
-(id)initWithIndexBar:(id)arg1 ;
-(void)selectionUpdated;
-(_UIFeedbackRetargetBehavior *)retargetFeedbackBehavior;
-(void)setRetargetFeedbackBehavior:(_UIFeedbackRetargetBehavior *)arg1 ;
-(void)userInteractionEnded;
-(void)userInteractionStarted;
-(void)userInteractionCancelled;
@end

