/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ISStoreURLOperationDelegate <ISURLOperationDelegate>
@optional
-(void)operation:(id)arg1 didAuthenticateWithDSID:(id)arg2;
-(BOOL)operation:(id)arg1 shouldSetStoreFrontID:(id)arg2;

@end

