/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Music.NotificationObserver : _UKNOWN_SUPERCLASS_ {

	 name;
	 object;
	 dispatchOnMainThread;
	 handler;

}
-(void)handleNotification:(id)arg1 ;
@end

