/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@class _TtC5Music21NowPlayingContentView, UILayoutGuide, UILabel, _TtC5Music16MiniPlayerButton, UIPanGestureRecognizer, UILongPressGestureRecognizer, _TtC5Music35NowPlayingTransportControlStackView, _TtC5Music25NowPlayingTransportButton;

@interface Music.MiniPlayerViewController : UIViewController <UIViewControllerTransitioningDelegate, UIGestureRecognizerDelegate> {

	 artworkView;
	 artworkLayoutGuide;
	 artworkConstraints;
	 nowPlayingItemTitleLabel;
	 miniPlayerButton;
	 panGestureRecognizer;
	 playbackCancellationGesture;
	 transportControlsController;
	 transportControlsStack;
	 playPauseButton;
	 playPauseButtonConfiguration;
	 skipButton;
	 skipButtonConfiguration;
	 bindings;
	 contextActionRegistration;
	 isPresentingNowPlaying;

}

@property (retain,nonatomic) _TtC5Music21NowPlayingContentView * artworkView; 
@property (retain,nonatomic) UILayoutGuide * artworkLayoutGuide; 
@property (retain,nonatomic) UILabel * nowPlayingItemTitleLabel; 
@property (retain,nonatomic) _TtC5Music16MiniPlayerButton * miniPlayerButton; 
@property (retain,nonatomic) UIPanGestureRecognizer * panGestureRecognizer; 
@property (retain,nonatomic) UILongPressGestureRecognizer * playbackCancellationGesture; 
@property (retain,nonatomic) _TtC5Music35NowPlayingTransportControlStackView * transportControlsStack; 
@property (retain,nonatomic) _TtC5Music25NowPlayingTransportButton * playPauseButton; 
@property (retain,nonatomic) _TtC5Music25NowPlayingTransportButton * skipButton; 
-(id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3 ;
-(id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3 ;
-(id)animationControllerForDismissedController:(id)arg1 ;
-(void)setArtworkLayoutGuide:(UILayoutGuide *)arg1 ;
-(UILabel *)nowPlayingItemTitleLabel;
-(void)setNowPlayingItemTitleLabel:(UILabel *)arg1 ;
-(_TtC5Music16MiniPlayerButton *)miniPlayerButton;
-(void)setMiniPlayerButton:(_TtC5Music16MiniPlayerButton *)arg1 ;
-(UILongPressGestureRecognizer *)playbackCancellationGesture;
-(void)setPlaybackCancellationGesture:(UILongPressGestureRecognizer *)arg1 ;
-(_TtC5Music35NowPlayingTransportControlStackView *)transportControlsStack;
-(void)setTransportControlsStack:(_TtC5Music35NowPlayingTransportControlStackView *)arg1 ;
-(void)beginNowPlayingPresentation;
-(void)accessibilityUpdateMetadata;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(UIPanGestureRecognizer *)panGestureRecognizer;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(_TtC5Music21NowPlayingContentView *)artworkView;
-(UILayoutGuide *)artworkLayoutGuide;
-(void)setSkipButton:(_TtC5Music25NowPlayingTransportButton *)arg1 ;
-(_TtC5Music25NowPlayingTransportButton *)skipButton;
-(void)setPanGestureRecognizer:(UIPanGestureRecognizer *)arg1 ;
-(_TtC5Music25NowPlayingTransportButton *)playPauseButton;
-(void)setPlayPauseButton:(_TtC5Music25NowPlayingTransportButton *)arg1 ;
-(void)setArtworkView:(_TtC5Music21NowPlayingContentView *)arg1 ;
@end

