/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIImageView, UILayoutGuide, UIStackView, UIButton, UIVisualEffectView;

@interface Music.ContextActionHeaderViewController : UIViewController {

	 fontCollection;
	 chevronImageView;
	 artworkComponent;
	 artworkGuide;
	 titleStack;
	 playButton;
	 visualEffectView;
	 didUsePlayHandler;
	 playHandler;
	 allowsChevron;

}

@property (retain,nonatomic) UIImageView * chevronImageView; 
@property (retain,nonatomic) UILayoutGuide * artworkGuide; 
@property (retain,nonatomic) UIStackView * titleStack; 
@property (retain,nonatomic) UIButton * playButton; 
@property (retain,nonatomic) UIVisualEffectView * visualEffectView; 
@property (assign,nonatomic) BOOL didUsePlayHandler; 
@property (copy,nonatomic) id playHandler; 
@property (assign,nonatomic) BOOL allowsChevron; 
-(UIImageView *)chevronImageView;
-(void)setChevronImageView:(UIImageView *)arg1 ;
-(UILayoutGuide *)artworkGuide;
-(void)setArtworkGuide:(UILayoutGuide *)arg1 ;
-(UIStackView *)titleStack;
-(void)setTitleStack:(UIStackView *)arg1 ;
-(BOOL)didUsePlayHandler;
-(void)setDidUsePlayHandler:(BOOL)arg1 ;
-(BOOL)allowsChevron;
-(void)setAllowsChevron:(BOOL)arg1 ;
-(void)updateMetadataFor:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(UIButton *)playButton;
-(void)setVisualEffectView:(UIVisualEffectView *)arg1 ;
-(UIVisualEffectView *)visualEffectView;
-(void)setPlayButton:(UIButton *)arg1 ;
-(id)playHandler;
-(void)setPlayHandler:(id)arg1 ;
@end

