/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSViewModel.h>

@class MPStoreItemMetadata, MPIdentifierSet, _TtC5Music21JSContainerDetailLink;

@interface Music.JSContainerDetail : Music.JSViewModel {

	 containerStoreItemMetadata;
	 prominentItemIdentifiers;
	 containerDetailLink;
	 footerViewModelKinds;
	 containerDetailDelegate;
	 kind;

}

@property (retain,nonatomic) MPStoreItemMetadata * containerStoreItemMetadata; 
@property (retain,nonatomic) MPIdentifierSet * prominentItemIdentifiers; 
@property (retain,nonatomic) _TtC5Music21JSContainerDetailLink * containerDetailLink; 
+(id)containerStoreItemMetadataDidChangeNotification;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(_TtC5Music21JSContainerDetailLink *)containerDetailLink;
-(void)setContainerDetailLink:(_TtC5Music21JSContainerDetailLink *)arg1 ;
-(MPStoreItemMetadata *)containerStoreItemMetadata;
-(void)setContainerStoreItemMetadata:(MPStoreItemMetadata *)arg1 ;
-(MPIdentifierSet *)prominentItemIdentifiers;
-(void)setProminentItemIdentifiers:(MPIdentifierSet *)arg1 ;
@end

