/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSString, UILabel, UIImageView, MusicAlertPresentationWindow;

@interface Music.ContextActionsHUDViewController : UIViewController {

	 type;
	 customMessage;
	 primaryLabel;
	 secondaryLabel;
	 imageView;
	 presentationWindow;
	 HUDView;

}

@property (copy,nonatomic) NSString * customMessage; 
@property (retain,nonatomic) UILabel * primaryLabel; 
@property (retain,nonatomic) UILabel * secondaryLabel; 
@property (retain,nonatomic) UIImageView * imageView; 
@property (readonly,nonatomic) double imagePaddingTop; 
@property (readonly,nonatomic) double primaryTextTopPaddingAdjustment; 
@property (retain,nonatomic) MusicAlertPresentationWindow * presentationWindow; 
-(NSString *)customMessage;
-(void)setCustomMessage:(NSString *)arg1 ;
-(void)setPrimaryLabel:(UILabel *)arg1 ;
-(double)imagePaddingTop;
-(double)primaryTextTopPaddingAdjustment;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(UIImageView *)imageView;
-(void)present;
-(UILabel *)secondaryLabel;
-(void)setSecondaryLabel:(UILabel *)arg1 ;
-(void)setImageView:(UIImageView *)arg1 ;
-(UILabel *)primaryLabel;
-(void)setPresentationWindow:(MusicAlertPresentationWindow *)arg1 ;
-(MusicAlertPresentationWindow *)presentationWindow;
@end

