/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSString;

@interface Music.JSObject : NSObject {

	 nativeBridgeIdentifier;

}

@property (readonly,nonatomic) NSDictionary * JSSerialized; 
@property (readonly,nonatomic) NSString * nativeBridgeIdentifier; 
@property (readonly,nonatomic) long long hash; 
-(NSDictionary *)JSSerialized;
-(NSString *)nativeBridgeIdentifier;
-(id)init;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(long long)hash;
@end

