/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIControl.h>

@class UILabel, UIView, UIImageView, NSMutableDictionary, MusicDownloadProgressView;

@interface MusicLibraryAddKeepLocalControl : UIControl {

	UILabel* _controlTitleLabel;
	UIView* _backgroundView;
	UIImageView* _controlImageView;
	NSMutableDictionary* _controlStatusTypeToTitle;
	long long _controlStatusRevision;
	MusicDownloadProgressView* _downloadProgressView;
	BOOL _hadFirstTouchHighlight;
	UIEdgeInsets _controlImageEdgeInsets;
	UIView* _transientContentView;
	long long _transientContentViewTransactionCount;
	BOOL _allowsAddImage;
	long long _displayStyle;
	MusicLibraryAddKeepLocalControlStatus _controlStatus;

}

@property (assign,nonatomic) BOOL allowsAddImage;                                              //@synthesize allowsAddImage=_allowsAddImage - In the implementation block
@property (assign,nonatomic) MusicLibraryAddKeepLocalControlStatus controlStatus;              //@synthesize controlStatus=_controlStatus - In the implementation block
@property (assign,nonatomic) long long displayStyle;                                           //@synthesize displayStyle=_displayStyle - In the implementation block
+(CGSize)_expectedSizeForControlStatusType:(long long)arg1 controlTitle:(id)arg2 hasControlImage:(BOOL)arg3 displayScale:(double)arg4 preferredHeight:(double)arg5 ;
+(id)_newControlTitleLabel;
+(id)_controlTitleFontForControlStatusType:(long long)arg1 ;
-(void)_updateControlStatusProperties;
-(void)_updateControlImageViewAnimation;
-(void)_updateBackgroundViewCornerRadius;
-(CGSize)maximumSizeWithPreferredHeight:(double)arg1 ;
-(id)titleForControlStatusType:(long long)arg1 ;
-(void)_updateControlTitleLabelVisualProperties;
-(void)_beginTransientContentViewTransaction;
-(void)_endTransientContentViewTransaction;
-(void)setControlStatus:(MusicLibraryAddKeepLocalControlStatus)arg1 animated:(BOOL)arg2 ;
-(id)_currentContentSuperview;
-(void)setAllowsAddImage:(BOOL)arg1 ;
-(void)setControlStatus:(MusicLibraryAddKeepLocalControlStatus)arg1 ;
-(void)setTitle:(id)arg1 forControlStatusType:(long long)arg2 ;
-(BOOL)allowsAddImage;
-(MusicLibraryAddKeepLocalControlStatus)controlStatus;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)didMoveToWindow;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)tintColorDidChange;
-(void)_removeAllAnimations:(BOOL)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setContentHorizontalAlignment:(long long)arg1 ;
-(long long)displayStyle;
-(void)setDisplayStyle:(long long)arg1 ;
-(void)_applicationWillEnterForegroundNotification:(id)arg1 ;
@end

