/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIButton;

@interface Music.ContextActionsButtonViewController : UIViewController {

	 button;
	 isSelected;

}

@property (readonly,nonatomic) UIButton * button; 
@property (assign,nonatomic) BOOL isSelected; 
-(UIButton *)button;
-(id)initWithCoder:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(BOOL)isSelected;
-(void)viewDidLoad;
-(void)setIsSelected:(BOOL)arg1 ;
@end

