/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.Bar.h>

@interface Music.SearchSourceBar : Music.Bar {

	 dataSource;
	 delegate;
	 segmentedControlShouldFitWidth;
	 segmentedControlMinimumWidth;
	 segmentedControl.storage;

}

@property (assign,nonatomic) BOOL segmentedControlShouldFitWidth; 
@property (assign,nonatomic) double segmentedControlMinimumWidth; 
@property (readonly,nonatomic) CGSize intrinsicContentSize; 
-(BOOL)segmentedControlShouldFitWidth;
-(void)setSegmentedControlShouldFitWidth:(BOOL)arg1 ;
-(double)segmentedControlMinimumWidth;
-(void)setSegmentedControlMinimumWidth:(double)arg1 ;
-(void)selectSourceAt:(long long)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(void)reloadData;
-(CGSize)intrinsicContentSize;
@end

