/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <MediaPlayerUI/MPUTheme.h>

@interface MusicAppTheme : MPUTheme
+(double)defaultLibraryAddKeepLocalControlHeight;
+(id)cloudDownloadImageForTintColor:(id)arg1 outlineColor:(id)arg2 traitCollection:(id)arg3 ;
+(id)actionCellImageTintColor;
+(id)nowPlayingSecondaryBackgroundColor;
+(id)searchGrayBackgroundColor;
+(id)ultralightGrey;
+(id)whiteNavigationBarTintColor;
+(id)grayNavigationBarTintColor;
+(id)nowPlayingIndicatorBackgroundColor;
+(id)nowPlayingChevronColor;
+(id)relatedContentBackgroundColor;
+(double)artworkListCornerRadius;
+(double)artworkGridCornerRadius;
+(id)shuffleAccessoryImage;
+(id)clearSinglePointImage;
+(id)singlePointImageUsingColor:(id)arg1 ;
+(id)stringForTimeSinceDate:(id)arg1 ;
+(id)shortStringForNumber:(long long)arg1 ;
+(CGSize)cloudDownloadImageSizeForTraitCollection:(id)arg1 ;
+(id)explicitString;
+(long long)preferredNumberOfGridColumnsWithBounds:(CGRect)arg1 ;
+(long long)preferredNumberOfPersonGridColumnsWithBounds:(CGRect)arg1 ;
+(long long)preferredNumberOfCustomRoomGridColumnsWithBounds:(CGRect)arg1 ;
+(double)stackedGridHorizontalSpacingWithBounds:(CGRect)arg1 ;
+(double)swipingGridHorizontalSpacingWithBounds:(CGRect)arg1 ;
+(id)tintColor;
+(id)titleColor;
+(id)hairlineColor;
+(id)timeFormatter;
+(id)artworkBorderColor;
+(id)subtitleColor;
+(id)systemLightGrayColor;
-(id)init;
@end

