/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@class NSString, _TtC5Music6JSMenu;

@interface Music.JSMenuItem : Music.JSObject {

	 title;
	 submenu;

}

@property (copy,nonatomic) NSString * title; 
@property (retain,nonatomic) _TtC5Music6JSMenu * submenu; 
@property (readonly,nonatomic) NSString * description; 
-(_TtC5Music6JSMenu *)submenu;
-(void)setSubmenu:(_TtC5Music6JSMenu *)arg1 ;
-(void)invokeMethod:(id)arg1 arguments:(id)arg2 ;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)description;
-(NSString *)title;
@end

