/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@interface Music.JSNetwork : Music.JSObject {

	 simplifiedNetworkType;
	 operatorName;
	 connectionTypeHeader;
	 networkTypeChangedNotificationObserver;
	 operatorNameChangedNotificationObserver;

}
-(id)init;
@end

