/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.VerticalLockupCollectionViewCell.h>

@class NSString;

@interface Music.FeaturedShowcaseCell : Music.VerticalLockupCollectionViewCell {

	 headline;
	 title;
	 subtitle;
	 descriptionText;
	 textComponents;

}

@property (copy,nonatomic) NSString * headline; 
@property (copy,nonatomic) NSString * title; 
@property (copy,nonatomic) NSString * subtitle; 
@property (copy,nonatomic) NSString * descriptionText; 
@property (assign,nonatomic) CGRect bounds; 
@property (assign,nonatomic) CGRect frame; 
+(double)preferredHeightWithTraitCollection:(id)arg1 width:(double)arg2 collectionView:(id)arg3 ;
+(id)reuseIdentifier;
+(void)setReuseIdentifier:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(CGRect)bounds;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(CGRect)frame;
-(void)setBounds:(CGRect)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(NSString *)title;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(NSString *)descriptionText;
-(void)setDescriptionText:(NSString *)arg1 ;
-(NSString *)headline;
-(void)setHeadline:(NSString *)arg1 ;
@end

