/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@interface Music.JSSubscriptionStatusRequest : Music.JSObject {

	 reason;
	 ignoreCache;
	 wantsPartialResults;
	 frozen;

}

@property (assign,nonatomic) BOOL ignoreCache; 
@property (assign,nonatomic) BOOL wantsPartialResults; 
-(void)invokeMethod:(id)arg1 arguments:(id)arg2 ;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(BOOL)ignoreCache;
-(void)setIgnoreCache:(BOOL)arg1 ;
-(BOOL)wantsPartialResults;
-(void)setWantsPartialResults:(BOOL)arg1 ;
@end

