/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class _TtC5Music20NavigationController;


@protocol Music.PopoverMenuControllerType
@property (assign,__weak,nonatomic) _TtC5Music20NavigationController * navigationController; 
@property (readonly,nonatomic) long long indexToPopToInsteadOfRoot; 
@required
-(void)traitCollectionDidChange:(id)arg1 newTraitCollection:(id)arg2;
-(long long)indexToPopToInsteadOfRoot;
-(_TtC5Music20NavigationController *)navigationController;
-(void)setNavigationController:(id)arg1;

@end

