/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/MPModelResponseSwiftShim.h>
#import <Music/Music.ContainerDetailAlbumNavigationHandleable.h>
#import <libobjc.A.dylib/MPModelResponseDetailedKeepLocalStatusRequesting.h>

@interface Music.PlaylistModelResponse : MPModelResponseSwiftShim <Music.ContainerDetailAlbumNavigationHandleable, MPModelResponseDetailedKeepLocalStatusRequesting> {

	 underlyingModelResponse;
	 underlyingResponseInvalidationObserver;

}

@property (readonly,nonatomic) id underlyingModelResponse; 
@property (retain,nonatomic) id results; 
-(/*^block*/id)navigationHandlerForItemAt:(id)arg1 sourceViewController:(id)arg2 ;
-(id)underlyingModelResponse;
-(id)initWithUnderlyingModelResponse:(id)arg1 ;
-(id)initWithRequest:(id)arg1 ;
-(id)results;
-(void)setResults:(id)arg1 ;
-(void)getChangeDetailsFromPreviousResponse:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)newOperationForDetailedKeepLocalStatusConfigurationForSectionAtIndex:(long long)arg1 responseHandler:(/*^block*/id)arg2 ;
@end

