/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIVisualEffectView.h>

@class UIColor;

@interface Music.NavigationBarBackgroundView : UIVisualEffectView {

	 backgroundTintColor;
	 shouldUseTraitCollectionGroupName;
	 tintView;
	 appearanceStorage;

}

@property (retain,nonatomic) UIColor * backgroundTintColor; 
@property (assign,nonatomic) BOOL shouldUseTraitCollectionGroupName; 
@property (retain,nonatomic) id appearanceStorage; 
-(BOOL)shouldUseTraitCollectionGroupName;
-(void)setShouldUseTraitCollectionGroupName:(BOOL)arg1 ;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id)initWithEffect:(id)arg1 ;
-(void)_setFrame:(CGRect)arg1 forceUpdateBackgroundImage:(BOOL)arg2 ;
-(void)updateBackgroundImage;
-(id)appearanceStorage;
-(void)setAppearanceStorage:(id)arg1 ;
-(void)setBackgroundTintColor:(UIColor *)arg1 ;
-(UIColor *)backgroundTintColor;
@end

