/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, NSString, UIColor;

@interface Music.OnboardingInstructionsView : UIView {

	 contentPosition;
	 contentInset;
	 explanationLabel;
	 titleLabel;
	 labelsStack;
	 titleText;
	 explanationText;

}

@property (assign,nonatomic) UIEdgeInsets contentInset; 
@property (retain,nonatomic) UILabel * explanationLabel; 
@property (retain,nonatomic) UILabel * titleLabel; 
@property (copy,nonatomic) NSString * titleText; 
@property (copy,nonatomic) NSString * explanationText; 
@property (retain,nonatomic) UIColor * backgroundColor; 
-(void)setExplanationLabel:(UILabel *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setBackgroundColor:(UIColor *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(UIColor *)backgroundColor;
-(UIEdgeInsets)contentInset;
-(void)setContentInset:(UIEdgeInsets)arg1 ;
-(UILabel *)titleLabel;
-(void)setTitleText:(NSString *)arg1 ;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(NSString *)titleText;
-(NSString *)explanationText;
-(UILabel *)explanationLabel;
-(void)setExplanationText:(NSString *)arg1 ;
-(void)pushLabelState;
-(void)popLabelState;
@end

