/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIView.h>

@class UIColor, NSString;

@interface Music.OnboardingProgressView : UIView {

	 fillColor;
	 title;
	 borderView.storage;
	 progressView.storage;
	 titleLabel;
	 progress;

}

@property (retain,nonatomic) UIColor * fillColor; 
@property (copy,nonatomic) NSString * title; 
@property (readonly,nonatomic) double accessibilityProgress; 
-(double)accessibilityProgress;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(NSString *)title;
-(void)tintColorDidChange;
-(void)setFillColor:(UIColor *)arg1 ;
-(UIColor *)fillColor;
-(void)setProgress:(double)arg1 animated:(BOOL)arg2 ;
@end

