/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIStackView.h>

@class NSArray;

@interface Music.TabItemsStack : UIStackView {

	 delegate;
	 tabBarItems;
	 selectedIndex;

}

@property (copy,nonatomic) NSArray * tabBarItems; 
@property (readonly,nonatomic) NSArray * buttons; 
@property (assign,nonatomic) long long selectedIndex; 
-(void)tabBarButtonTapped:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(long long)selectedIndex;
-(void)setSelectedIndex:(long long)arg1 ;
-(NSArray *)buttons;
-(void)setTabBarItems:(NSArray *)arg1 ;
-(NSArray *)tabBarItems;
-(void)removeAllArrangedSubviews;
@end

