/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UICollectionViewDelegateTableLayout.h>

@class UIView, _TtC5Music32CompositeComponentCollectionView;

@interface Music.ContainerDetailAccessoryViewController : UIViewController <UICollectionViewDelegateTableLayout> {

	 modelResponse;
	 headerView;
	 wantsHeaderViewPadding;
	 collectionView.storage;
	 textDrawingCache;
	 artworkDrawingContext;

}

@property (retain,nonatomic) id modelResponse; 
@property (retain,nonatomic) UIView * headerView; 
@property (assign,nonatomic) BOOL wantsHeaderViewPadding; 
@property (retain,nonatomic) _TtC5Music32CompositeComponentCollectionView * collectionView; 
@property (readonly,nonatomic) _TtC5Music32CompositeComponentCollectionView * compositeComponentCollectionView; 
-(id)modelResponse;
-(void)setModelResponse:(id)arg1 ;
-(_TtC5Music32CompositeComponentCollectionView *)compositeComponentCollectionView;
-(BOOL)wantsHeaderViewPadding;
-(void)setWantsHeaderViewPadding:(BOOL)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(_TtC5Music32CompositeComponentCollectionView *)collectionView;
-(void)viewDidLoad;
-(UIView *)headerView;
-(void)setHeaderView:(UIView *)arg1 ;
-(void)setCollectionView:(_TtC5Music32CompositeComponentCollectionView *)arg1 ;
-(double)collectionView:(id)arg1 heightForHeaderViewInTableLayout:(id)arg2 ;
@end

