/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.VerticalLockupCollectionViewCell.h>

@class NSString;

@interface Music.FeaturedPlaylistCell : Music.VerticalLockupCollectionViewCell {

	 name;
	 descriptionText;
	 textComponents;

}

@property (copy,nonatomic) NSString * name; 
@property (copy,nonatomic) NSString * descriptionText; 
+(double)preferredHeightWithTraitCollection:(id)arg1 width:(double)arg2 ;
+(UIEdgeInsets)visualContentInsets;
+(id)reuseIdentifier;
+(void)setReuseIdentifier:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)descriptionText;
-(void)setDescriptionText:(NSString *)arg1 ;
@end

