/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@class NSString, NSURL, NSArray, NSDate;

@interface Music.JSCookie : Music.JSObject {

	 name;
	 value;
	 originURL;
	 version;
	 domain;
	 path;
	 isSecure;
	 comment;
	 commentURL;
	 isSessionOnly;
	 maximumAge;
	 portList;
	 expirationDate;

}

@property (copy,nonatomic) NSString * name; 
@property (copy,nonatomic) NSString * value; 
@property (copy,nonatomic) NSURL * originURL; 
@property (copy,nonatomic) NSString * domain; 
@property (copy,nonatomic) NSString * path; 
@property (copy,nonatomic) NSString * comment; 
@property (copy,nonatomic) NSURL * commentURL; 
@property (copy,nonatomic) NSArray * portList; 
@property (copy,nonatomic) NSDate * expirationDate; 
-(void)invokeMethod:(id)arg1 arguments:(id)arg2 ;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(id)initWithNativeCookie:(id)arg1 forInitialSetup:(BOOL)arg2 ;
-(NSURL *)originURL;
-(void)setOriginURL:(NSURL *)arg1 ;
-(void)setCommentURL:(NSURL *)arg1 ;
-(void)setPortList:(NSArray *)arg1 ;
-(NSURL *)commentURL;
-(NSArray *)portList;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)domain;
-(NSString *)path;
-(NSString *)value;
-(void)setValue:(NSString *)arg1 ;
-(void)setPath:(NSString *)arg1 ;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(void)setComment:(NSString *)arg1 ;
-(NSString *)comment;
-(void)setDomain:(NSString *)arg1 ;
@end

