/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MediaPlayer/MPModelObject.h>

@class NSString, NSDate, NSAttributedString, MusicStoreBrowseContentItem, MusicModelConnectUser, MPArtworkCatalog;

@interface MusicModelConnectFeedItem : MPModelObject {

	BOOL _liked;
	NSString* _postID;
	NSDate* _timestamp;
	NSAttributedString* _text;
	long long _numberOfLikes;
	long long _numberOfPlays;
	long long _numberOfComments;
	double _artworkAspectRatio;
	MusicStoreBrowseContentItem* _contentItem;
	MusicModelConnectUser* _owner;
	MusicModelConnectUser* _admin;
	/*^block*/id _artworkCatalogBlock;

}

@property (nonatomic,copy) NSString * postID;                                        //@synthesize postID=_postID - In the implementation block
@property (nonatomic,copy) NSDate * timestamp;                                       //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,retain) NSAttributedString * text;                              //@synthesize text=_text - In the implementation block
@property (assign,nonatomic) long long numberOfLikes;                                //@synthesize numberOfLikes=_numberOfLikes - In the implementation block
@property (assign,nonatomic) long long numberOfPlays;                                //@synthesize numberOfPlays=_numberOfPlays - In the implementation block
@property (assign,nonatomic) long long numberOfComments;                             //@synthesize numberOfComments=_numberOfComments - In the implementation block
@property (assign,nonatomic) double artworkAspectRatio;                              //@synthesize artworkAspectRatio=_artworkAspectRatio - In the implementation block
@property (assign,nonatomic) BOOL liked;                                             //@synthesize liked=_liked - In the implementation block
@property (nonatomic,retain) MusicStoreBrowseContentItem * contentItem;              //@synthesize contentItem=_contentItem - In the implementation block
@property (nonatomic,retain) MusicModelConnectUser * owner;                          //@synthesize owner=_owner - In the implementation block
@property (nonatomic,retain) MusicModelConnectUser * admin;                          //@synthesize admin=_admin - In the implementation block
@property (nonatomic,copy) id artworkCatalogBlock;                                   //@synthesize artworkCatalogBlock=_artworkCatalogBlock - In the implementation block
@property (nonatomic,readonly) MPArtworkCatalog * artworkCatalog; 
+(id)__postID__KEY;
+(id)__MusicModelPropertyConnectFeedItemPostID__PROPERTY;
+(id)__timestamp__KEY;
+(id)__MusicModelPropertyConnectFeedItemTimestamp__PROPERTY;
+(id)__MusicModelPropertyConnectFeedItemText__PROPERTY;
+(id)__numberOfLikes__KEY;
+(id)__MusicModelPropertyConnectFeedItemNumberOfLikes__PROPERTY;
+(id)__numberOfPlays__KEY;
+(id)__MusicModelPropertyConnectFeedItemNumberOfPlays__PROPERTY;
+(id)__numberOfComments__KEY;
+(id)__MusicModelPropertyConnectFeedItemNumberOfComments__PROPERTY;
+(id)__liked__KEY;
+(id)__MusicModelPropertyConnectFeedItemLiked__PROPERTY;
+(id)__MusicModelPropertyConnectFeedItemArtwork__PROPERTY;
+(id)__artworkAspectRatio__KEY;
+(id)__MusicModelPropertyConnectFeedItemArtworkAspectRatio__PROPERTY;
+(id)__contentItem__KEY;
+(id)__MusicModelRelationshipConnectFeedItemContentItem__PROPERTY;
+(id)__MusicModelRelationshipConnectFeedItemOwner__PROPERTY;
+(id)__admin__KEY;
+(id)__MusicModelRelationshipConnectFeedItemAdmin__PROPERTY;
+(id)__text__KEY;
+(id)__artworkCatalogBlock__KEY;
+(id)__owner__KEY;
-(NSString *)postID;
-(void)setPostID:(NSString *)arg1 ;
-(long long)numberOfPlays;
-(void)setNumberOfPlays:(long long)arg1 ;
-(long long)numberOfComments;
-(void)setNumberOfComments:(long long)arg1 ;
-(NSDate *)timestamp;
-(void)setTimestamp:(NSDate *)arg1 ;
-(NSAttributedString *)text;
-(void)setText:(NSAttributedString *)arg1 ;
-(MusicModelConnectUser *)owner;
-(void)setOwner:(MusicModelConnectUser *)arg1 ;
-(MPArtworkCatalog *)artworkCatalog;
-(void)setArtworkCatalogBlock:(id)arg1 ;
-(id)artworkCatalogBlock;
-(void)setLiked:(BOOL)arg1 ;
-(BOOL)liked;
-(long long)numberOfLikes;
-(MusicStoreBrowseContentItem *)contentItem;
-(void)setContentItem:(MusicStoreBrowseContentItem *)arg1 ;
-(double)artworkAspectRatio;
-(void)setArtworkAspectRatio:(double)arg1 ;
-(void)setNumberOfLikes:(long long)arg1 ;
-(void)setAdmin:(MusicModelConnectUser *)arg1 ;
-(MusicModelConnectUser *)admin;
@end

