/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UICollectionViewDataSource.h>
#import <UIKit/UICollectionViewDelegate.h>
#import <UIKit/UICollectionViewDelegateTableLayout.h>
#import <libobjc.A.dylib/MPStoreDownloadManagerObserver.h>

@class _TtC5Music32CompositeComponentCollectionView, NSString;

@interface Music.LibraryMenuViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateTableLayout, MPStoreDownloadManagerObserver> {

	 editingDelegate;
	 selectionDelegate;
	 collectionView.storage;
	 needsVisibleIdentifierUpdate;
	 editButton;
	 editButtonAttributedTitle;
	 sizingButton;
	 doneButtonAttributedTitle;
	 pageHeaderContentViewController.storage;
	 deferredCollectionViewLayoutUpdate;
	 waitingForLayoutSubviews;
	 bindings;
	 adminAuthors;
	 textDrawingCache;
	 preferredContentSizeDidChangeObserver;
	 _editingActiveIdentifiers;
	 _identifiersForDataSource;

}

@property (retain,nonatomic) _TtC5Music32CompositeComponentCollectionView * collectionView; 
@property (copy,nonatomic) NSString * title; 
@property (readonly,nonatomic) _TtC5Music32CompositeComponentCollectionView * compositeComponentCollectionView; 
-(void)compositeComponentWillMoveToParentViewController:(id)arg1 ;
-(void)compositeComponentDidMoveToParentViewController:(id)arg1 ;
-(_TtC5Music32CompositeComponentCollectionView *)compositeComponentCollectionView;
-(void)updateMetricsForCollectionViewTableLayout:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)setTitle:(NSString *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInCollectionView:(id)arg1 ;
-(id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3 ;
-(BOOL)collectionView:(id)arg1 canMoveItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(BOOL)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(NSString *)title;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1 ;
-(_TtC5Music32CompositeComponentCollectionView *)collectionView;
-(id)contentScrollView;
-(void)viewDidLoad;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3 ;
-(void)setCollectionView:(_TtC5Music32CompositeComponentCollectionView *)arg1 ;
-(long long)collectionView:(id)arg1 tableLayout:(id)arg2 editingStyleForRowAtIndexPath:(id)arg3 ;
-(double)collectionView:(id)arg1 tableLayout:(id)arg2 heightForHeaderInSection:(long long)arg3 ;
-(void)downloadManager:(id)arg1 didAddDownloads:(id)arg2 removeDownloads:(id)arg3 ;
-(void)music_viewInheritedLayoutInsetsDidChange;
@end

