/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.HorizontalLockupCollectionViewCell.h>

@class NSString;

@interface Music.UserDetailsCell : Music.HorizontalLockupCollectionViewCell {

	 name;
	 nickname;
	 textComponents;

}

@property (copy,nonatomic) NSString * name; 
@property (copy,nonatomic) NSString * nickname; 
+(CGSize)defaultSizeWithTraitCollection:(id)arg1 containerSize:(CGSize)arg2 ;
+(id)reuseIdentifier;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)nickname;
-(void)setNickname:(NSString *)arg1 ;
@end

