/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIScrollViewDelegate.h>

@class NSArray, UIScrollView;

@interface Music.ThreePaneScrollingViewController : UIViewController <UIScrollViewDelegate> {

	 viewControllers;
	 leadingSeparator;
	 trailingSeparator;
	 navigationBars;
	 _tiledSize;
	 centerPaneWidth;
	 _alwaysUseBackButton;
	 scrollView;
	 _insetsForChildren;
	 viewControllerAppearanceStateMap;
	 appearanceState;

}

@property (copy,nonatomic) NSArray * viewControllers; 
@property (assign,nonatomic) double centerPaneWidth; 
@property (assign,nonatomic) BOOL alwaysUseBackButton; 
@property (readonly,nonatomic) UIScrollView * scrollView; 
@property (assign,nonatomic) UIEdgeInsets _insetsForChildren;                                       //@synthesize insetsForChildren=_insetsForChildren - In the implementation block
@property (assign,nonatomic) UIEdgeInsets _navigationControllerContentInsetAdjustment; 
@property (readonly,nonatomic) BOOL shouldAutomaticallyForwardAppearanceMethods; 
+(double)minimumWidthNeededForRegularLayout;
-(double)centerPaneWidth;
-(void)setCenterPaneWidth:(double)arg1 ;
-(BOOL)alwaysUseBackButton;
-(void)setAlwaysUseBackButton:(BOOL)arg1 ;
-(UIEdgeInsets)_insetsForChildren;
-(void)set_insetsForChildren:(UIEdgeInsets)arg1 ;
-(void)_updateCenterBackAlphaForScrollWithScrollView:(id)arg1 ;
-(void)revealLeadingPaneWithAnimated:(BOOL)arg1 ;
-(void)revealTrailingPaneWithAnimated:(BOOL)arg1 ;
-(void)_addViewControllersWithViewControllers:(id)arg1 ;
-(void)_adjustTraitCollectionsWithViewControllers:(id)arg1 ;
-(void)_addNavigationBarFor:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(CGPoint*)arg3 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)_setNavigationControllerContentInsetAdjustment:(UIEdgeInsets)arg1 ;
-(void)viewDidLoad;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)showViewController:(id)arg1 sender:(id)arg2 ;
-(UIEdgeInsets)_navigationControllerContentInsetAdjustment;
-(NSArray *)viewControllers;
-(UIScrollView *)scrollView;
-(void)setViewControllers:(NSArray *)arg1 ;
@end

