/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MusicPhysicsWrapper : NSObject {

	id _unwrappedObject;

}

@property (nonatomic,copy) id unwrappedObject;              //@synthesize unwrappedObject=_unwrappedObject - In the implementation block
+(Class)_classForWrappedType;
+(id)cachedWrappedObject:(id)arg1 ;
-(id)initWithWrappedObject:(id)arg1 ;
-(id)unwrappedObject;
-(void)setUnwrappedObject:(id)arg1 ;
-(id)init;
@end

