/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.PopoverMenuControllerType.h>
#import <UIKit/UIPopoverPresentationControllerDelegate.h>

@class _TtC5Music20NavigationController;

@interface Music.LibraryPopoverMenuController : NSObject <Music.PopoverMenuControllerType, UIPopoverPresentationControllerDelegate> {

	 navigationController;
	 traitCollection;
	 popoverIsShown;

}

@property (assign,__weak,nonatomic) _TtC5Music20NavigationController * navigationController; 
@property (readonly,nonatomic) long long indexToPopToInsteadOfRoot; 
+(id)navigationPopoverButtonWithTitle:(id)arg1 traitCollection:(id)arg2 ;
-(void)traitCollectionDidChange:(id)arg1 newTraitCollection:(id)arg2 ;
-(long long)indexToPopToInsteadOfRoot;
-(void)libraryMenuDidSelectViewController:(id)arg1 overrideTraitCollection:(id)arg2 dismiss:(BOOL)arg3 ;
-(void)libraryMenuWasPopped:(id)arg1 ;
-(void)presentPopoverWithSender:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(_TtC5Music20NavigationController *)navigationController;
-(void)popoverPresentationControllerDidDismissPopover:(id)arg1 ;
-(void)setNavigationController:(_TtC5Music20NavigationController *)arg1 ;
-(id)initWithNavigationController:(id)arg1 ;
@end

