/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MediaPlayer/MPModelRequest.h>

@class _TtC5Music13JSConnectFeed;

@interface Music.JSConnectFeedModelRequest : MPModelRequest {

	 connectFeed;
	 previousResponse;

}

@property (retain,nonatomic) _TtC5Music13JSConnectFeed * connectFeed; 
-(id)initWithConnectFeed:(id)arg1 ;
-(_TtC5Music13JSConnectFeed *)connectFeed;
-(void)setConnectFeed:(_TtC5Music13JSConnectFeed *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(id)copyWithZone:(void*)arg1 ;
-(id)newOperationWithResponseHandler:(/*^block*/id)arg1 ;
@end

