/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <Music/Music.HorizontalLockupCollectionViewCell.h>

@class NSString;

@interface Music.PersonCell : Music.HorizontalLockupCollectionViewCell {

	 personName;
	 compactArtworkSize;
	 regularArtworkSize;
	 compactArtworkEdgeInsets;
	 regularArtworkEdgeInsets;
	 trailingSeparatorInset;
	 textComponents;

}

@property (copy,nonatomic) NSString * personName; 
@property (assign,nonatomic) CGSize compactArtworkSize; 
@property (assign,nonatomic) CGSize regularArtworkSize; 
@property (assign,nonatomic) UIEdgeInsets compactArtworkEdgeInsets; 
@property (assign,nonatomic) UIEdgeInsets regularArtworkEdgeInsets; 
@property (assign,nonatomic) double trailingSeparatorInset; 
+(CGSize)defaultSizeWithTraitCollection:(id)arg1 containerSize:(CGSize)arg2 ;
+(CGSize)defaultSizeWithTraitCollection:(id)arg1 artworkSize:(CGSize)arg2 artworkEdgeInsets:(UIEdgeInsets)arg3 containerSize:(CGSize)arg4 ;
+(id)reuseIdentifier;
-(CGSize)compactArtworkSize;
-(void)setCompactArtworkSize:(CGSize)arg1 ;
-(CGSize)regularArtworkSize;
-(void)setRegularArtworkSize:(CGSize)arg1 ;
-(UIEdgeInsets)compactArtworkEdgeInsets;
-(void)setCompactArtworkEdgeInsets:(UIEdgeInsets)arg1 ;
-(UIEdgeInsets)regularArtworkEdgeInsets;
-(void)setRegularArtworkEdgeInsets:(UIEdgeInsets)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)setTrailingSeparatorInset:(double)arg1 ;
-(double)trailingSeparatorInset;
-(NSString *)personName;
-(void)setPersonName:(NSString *)arg1 ;
@end

