/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@class NSDictionary, NSString;

@interface Music.JSArtwork : Music.JSObject {

	 artworkDelegate;
	 storeLookupDictionary;
	 cropStyle;
	 treatment;

}

@property (copy,nonatomic) NSDictionary * storeLookupDictionary; 
@property (copy,nonatomic) NSString * cropStyle; 
-(void)invokeMethod:(id)arg1 arguments:(id)arg2 ;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(NSDictionary *)storeLookupDictionary;
-(void)setStoreLookupDictionary:(NSDictionary *)arg1 ;
-(id)artworkCatalogWithDefaultCropStyle:(id)arg1 ;
-(void)setCropStyle:(NSString *)arg1 ;
-(NSString *)cropStyle;
@end

