/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.AdaptiveSplayedNavigationController.h>

@class _TtC5Music30JSStoreBrowseTabViewController;

@interface Music.StoreBrowseNavigationController : Music.AdaptiveSplayedNavigationController {

	 loadingViewController;
	 buttonInstalledViewController;
	 firstMenuItemFromBrowseRootViewController;

}

@property (readonly,nonatomic) _TtC5Music30JSStoreBrowseTabViewController * browseRootViewController; 
-(_TtC5Music30JSStoreBrowseTabViewController *)browseRootViewController;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)viewDidLoad;
-(void)showViewController:(id)arg1 sender:(id)arg2 ;
@end

