/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MediaPlayer/MPModelObject.h>

@class MusicStoreBrowseContentItem, NSString;

@interface MusicModelShelfItem : MPModelObject {

	MusicStoreBrowseContentItem* _contentItem;
	NSString* _headlineText;
	NSString* _titleText;
	NSString* _subtitleText;
	NSString* _descriptionText;
	/*^block*/id _backgroundArtworkCatalogBlock;

}

@property (nonatomic,retain) MusicStoreBrowseContentItem * contentItem;              //@synthesize contentItem=_contentItem - In the implementation block
@property (nonatomic,copy) NSString * headlineText;                                  //@synthesize headlineText=_headlineText - In the implementation block
@property (nonatomic,copy) NSString * titleText;                                     //@synthesize titleText=_titleText - In the implementation block
@property (nonatomic,copy) NSString * subtitleText;                                  //@synthesize subtitleText=_subtitleText - In the implementation block
@property (nonatomic,copy) NSString * descriptionText;                               //@synthesize descriptionText=_descriptionText - In the implementation block
@property (nonatomic,copy) id backgroundArtworkCatalogBlock;                         //@synthesize backgroundArtworkCatalogBlock=_backgroundArtworkCatalogBlock - In the implementation block
+(id)__contentItem__KEY;
+(id)__titleText__KEY;
+(id)__subtitleText__KEY;
+(id)__headlineText__KEY;
+(id)__backgroundArtworkCatalogBlock__KEY;
+(id)__MusicModelRelationshipShelfItemContentItem__PROPERTY;
+(id)__MusicModelPropertyShelfItemHeadlineText__PROPERTY;
+(id)__MusicModelPropertyShelfItemTitleText__PROPERTY;
+(id)__MusicModelPropertyShelfItemSubtitleText__PROPERTY;
+(id)__MusicModelPropertyShelfItemDescriptionText__PROPERTY;
+(id)__MusicModelPropertyShelfItemBackgroundArtwork__PROPERTY;
+(id)requiredStoreLibraryPersonalizationProperties;
+(id)__descriptionText__KEY;
-(id)backgroundArtworkCatalogBlock;
-(id)backgroundArtworkCatalog;
-(NSString *)headlineText;
-(void)setHeadlineText:(NSString *)arg1 ;
-(void)setBackgroundArtworkCatalogBlock:(id)arg1 ;
-(id)storeContentItemObject;
-(id)storeContentItemObjectPropertiesFor:(id)arg1 ;
-(void)setTitleText:(NSString *)arg1 ;
-(NSString *)titleText;
-(NSString *)descriptionText;
-(void)setDescriptionText:(NSString *)arg1 ;
-(id)relativeModelObjectForStoreLibraryPersonalization;
-(id)objectWithStoreLibraryPersonalizationRelativeModelObject:(id)arg1 ;
-(id)personalizationScopedPropertiesForProperties:(id)arg1 ;
-(void)setSubtitleText:(NSString *)arg1 ;
-(MusicStoreBrowseContentItem *)contentItem;
-(void)setContentItem:(MusicStoreBrowseContentItem *)arg1 ;
-(NSString *)subtitleText;
@end

