/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:22:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface MusicMonogramArtworkToken : NSObject <NSCopying> {

	NSString* _fullName;
	long long _style;

}

@property (nonatomic,copy) NSString * fullName;              //@synthesize fullName=_fullName - In the implementation block
@property (assign,nonatomic) long long style;                //@synthesize style=_style - In the implementation block
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(long long)style;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setStyle:(long long)arg1 ;
-(void)setFullName:(NSString *)arg1 ;
-(NSString *)fullName;
@end

