/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/MPModelResponseSwiftShim.h>
#import <libobjc.A.dylib/MPModelResponseDetailedKeepLocalStatusRequesting.h>

@interface Music.JSShelfModelResponse : MPModelResponseSwiftShim <MPModelResponseDetailedKeepLocalStatusRequesting> {

	 sectionsDidChangeNotificationObserver;
	 personalizationResponseInvalidationObserver;
	 personalizationResponse;
	 jsResults;

}

@property (readonly,nonatomic) id jsResults; 
-(id)jsResults;
-(id)initWithRequest:(id)arg1 ;
-(id)newOperationForDetailedKeepLocalStatusConfigurationForSectionAtIndex:(long long)arg1 responseHandler:(/*^block*/id)arg2 ;
@end

