/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music.JSObject.h>

@class _TtC5Music16JSPlaybackIntent;

@interface Music.JSSegue : Music.JSObject {

	 playbackIntent;

}

@property (retain,nonatomic) _TtC5Music16JSPlaybackIntent * playbackIntent; 
-(void)invokeMethod:(id)arg1 arguments:(id)arg2 ;
-(void)updateProperty:(id)arg1 value:(id)arg2 ;
-(_TtC5Music16JSPlaybackIntent *)playbackIntent;
-(void)setPlaybackIntent:(_TtC5Music16JSPlaybackIntent *)arg1 ;
@end

