/*
* This header is generated by classdump-dyld 1.0
* on Monday, February 20, 2017 at 11:23:00 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIView.h>

@interface Music.NowPlayingScrollingTipView : UIView {

	 doneButtonHandler;
	 imageView;
	 titleLabel;
	 subtitleLabel;
	 doneButton;
	 visualEffectView;
	 doneEventHandler;

}

@property (copy,nonatomic) id doneButtonHandler; 
-(id)doneButtonHandler;
-(void)setDoneButtonHandler:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

