/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:26:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIViewControllerAnimatedTransitioning <NSObject>
@optional
-(id)interruptibleAnimatorForTransition:(id)arg1;
-(void)animationEnded:(BOOL)arg1;

@required
-(double)transitionDuration:(id)arg1;
-(void)animateTransition:(id)arg1;

@end

