/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:26:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WACollectionViewLayoutProtocol <NSObject>
@required
-(double)cityViewPanOffsetForCell:(id)arg1 indexPath:(id)arg2 contentOffset:(CGPoint)arg3;

@end

