/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:26:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UIViewController.h>
#import <Weather/WACardCollectionViewControllerDelegate.h>
#import <Weather/WAPageCollectionViewControllerDelegate.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <UIKit/UISplitViewControllerDelegate.h>
#import <Weather/WACollectionViewTransitionDelegate.h>
#import <Weather/WACityPickerViewDelegate.h>
#import <Weather/WeatherUpdaterDelegate.h>

@protocol WAContainerViewControllerDelegate;
@class UISplitViewController, WAPageCollectionViewController, WACardCollectionViewController, NSArray, WACollectionViewTransitionManager, NSTimer, WACityPickerViewController, UINavigationController, WeatherPreferences, City, NSString;

@interface WAContainerViewController : UIViewController <WACardCollectionViewControllerDelegate, WAPageCollectionViewControllerDelegate, UINavigationControllerDelegate, UISplitViewControllerDelegate, WACollectionViewTransitionDelegate, WACityPickerViewDelegate, WeatherUpdaterDelegate> {

	BOOL _shouldReloadCardCitiesAfterReorder;
	BOOL _shouldSetCardCitiesAfterReorder;
	BOOL _performedInitialCityLoad;
	BOOL _viewDidAppear;
	id<WAContainerViewControllerDelegate> _delegate;
	UISplitViewController* _splitViewController;
	WAPageCollectionViewController* _pageController;
	WACardCollectionViewController* _cardController;
	NSArray* _cities;
	WACollectionViewTransitionManager* _transitionManager;
	NSTimer* _updateTimer;
	WACityPickerViewController* _cityPickerViewController;
	UINavigationController* _cityPickerNavigationController;
	WeatherPreferences* _preferences;

}

@property (nonatomic,retain) NSArray * cities;                                                     //@synthesize cities=_cities - In the implementation block
@property (nonatomic,retain) WACollectionViewTransitionManager * transitionManager;                //@synthesize transitionManager=_transitionManager - In the implementation block
@property (assign,nonatomic) BOOL shouldReloadCardCitiesAfterReorder;                              //@synthesize shouldReloadCardCitiesAfterReorder=_shouldReloadCardCitiesAfterReorder - In the implementation block
@property (assign,nonatomic) BOOL shouldSetCardCitiesAfterReorder;                                 //@synthesize shouldSetCardCitiesAfterReorder=_shouldSetCardCitiesAfterReorder - In the implementation block
@property (nonatomic,retain) NSTimer * updateTimer;                                                //@synthesize updateTimer=_updateTimer - In the implementation block
@property (nonatomic,retain) WACityPickerViewController * cityPickerViewController;                //@synthesize cityPickerViewController=_cityPickerViewController - In the implementation block
@property (nonatomic,retain) UINavigationController * cityPickerNavigationController;              //@synthesize cityPickerNavigationController=_cityPickerNavigationController - In the implementation block
@property (assign,nonatomic) BOOL performedInitialCityLoad;                                        //@synthesize performedInitialCityLoad=_performedInitialCityLoad - In the implementation block
@property (assign,nonatomic) BOOL viewDidAppear;                                                   //@synthesize viewDidAppear=_viewDidAppear - In the implementation block
@property (nonatomic,readonly) WeatherPreferences * preferences;                                   //@synthesize preferences=_preferences - In the implementation block
@property (assign,nonatomic,__weak) id<WAContainerViewControllerDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UISplitViewController * splitViewController;                          //@synthesize splitViewController=_splitViewController - In the implementation block
@property (nonatomic,retain) WAPageCollectionViewController * pageController;                      //@synthesize pageController=_pageController - In the implementation block
@property (nonatomic,retain) WACardCollectionViewController * cardController;                      //@synthesize cardController=_cardController - In the implementation block
@property (readonly) City * activeCity; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)_shouldForwardViewWillTransitionToSize;
-(void)setActiveCityIndex:(unsigned long long)arg1 ;
-(void)pageCollectionViewController:(id)arg1 showCardListFromCityAtIndex:(long long)arg2 ;
-(City *)activeCity;
-(void)_updateSplitViewPreferredDisplayMode;
-(void)_updateLocalWeather;
-(void)_updateOverrideTraitCollectionWithSize:(CGSize)arg1 ;
-(WACollectionViewTransitionManager *)transitionManager;
-(void)setCities:(id)arg1 reloadUI:(BOOL)arg2 ;
-(void)setShouldSetCardCitiesAfterReorder:(BOOL)arg1 ;
-(void)setShouldReloadCardCitiesAfterReorder:(BOOL)arg1 ;
-(BOOL)_splitViewIsCollapsed;
-(void)reloadFailedCities;
-(WACityPickerViewController *)cityPickerViewController;
-(void)_prepareToShowPageViewControllerForInitialAppSetup;
-(void)updateAllCitiesFromTimer:(id)arg1 ;
-(void)hideLocationPickerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)reloadLocalCity;
-(void)updateAllCities;
-(BOOL)performedInitialCityLoad;
-(void)setPerformedInitialCityLoad:(BOOL)arg1 ;
-(id)_cityOverrides;
-(void)discardOldData;
-(void)showCardListFromCityAtIndex:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)showLocationPickerAnimated:(BOOL)arg1 ;
-(void)_notifyOfCityListPrefChange;
-(void)_updateCollectionViewsForChange:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(void)deleteCity:(id)arg1 animate:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)_deleteCityAtIndex:(unsigned long long)arg1 animate:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)_exchangeCityAtIndex:(long long)arg1 withCityAtIndex:(long long)arg2 saveImmediately:(BOOL)arg3 ;
-(void)_updateCollectionViewsForChange:(/*^block*/id)arg1 shouldAnimateBlock:(/*^block*/id)arg2 completion:(/*^block*/id)arg3 ;
-(id)displayedLocalWeatherCity;
-(void)addLocalWeatherCityIfNeeded:(/*^block*/id)arg1 ;
-(id)controllerForCollectionView:(id)arg1 ;
-(void)deleteCityAtIndex:(unsigned long long)arg1 ;
-(BOOL)shouldSetCardCitiesAfterReorder;
-(BOOL)shouldReloadCardCitiesAfterReorder;
-(void)cardCollectionViewController:(id)arg1 showCityAtIndex:(long long)arg2 ;
-(void)cardCollectionViewController:(id)arg1 showCityAtIndex:(long long)arg2 animated:(BOOL)arg3 ;
-(void)cardCollectionViewController:(id)arg1 showCityPickerAnimated:(BOOL)arg2 ;
-(void)cardCollectionViewController:(id)arg1 exchangeCityAtIndex:(long long)arg2 withCityAtIndex:(long long)arg3 ;
-(void)cardCollectionViewControllerDidFinishReorder:(id)arg1 ;
-(void)cardCollectionViewController:(id)arg1 deleteCityAtIndex:(long long)arg2 ;
-(void)cardCollectionViewControllerPreviewDidDismiss;
-(BOOL)collectionViewTransitionManager:(id)arg1 canStartPinchingCityAtIndex:(long long)arg2 ;
-(void)cityPickerViewController:(id)arg1 didPickLocation:(id)arg2 ;
-(void)cityPickerViewController:(id)arg1 hideLocationPickerAnimated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)refreshForLocaleChange;
-(void)purgeTransientCities;
-(void)reloadCitiesAfterExternalAddition;
-(void)reloadCities;
-(void)reloadCitiesFromPrefs;
-(void)deleteCity:(id)arg1 ;
-(void)exchangeCityAtIndex:(long long)arg1 withCityAtIndex:(long long)arg2 ;
-(void)updateUserCitiesWithCompletion:(/*^block*/id)arg1 ;
-(void)updateLocalCityWithCompletion:(/*^block*/id)arg1 ;
-(void)setCityPickerViewController:(WACityPickerViewController *)arg1 ;
-(UINavigationController *)cityPickerNavigationController;
-(void)setCityPickerNavigationController:(UINavigationController *)arg1 ;
-(id)init;
-(void)setDelegate:(id<WAContainerViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<WAContainerViewControllerDelegate>)delegate;
-(long long)preferredStatusBarStyle;
-(unsigned long long)supportedInterfaceOrientations;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotate;
-(void)suspend;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(UISplitViewController *)splitViewController;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)willTransitionToTraitCollection:(id)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2 ;
-(id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4 ;
-(void)resume;
-(WeatherPreferences *)preferences;
-(NSTimer *)updateTimer;
-(void)setUpdateTimer:(NSTimer *)arg1 ;
-(BOOL)splitViewController:(id)arg1 showDetailViewController:(id)arg2 sender:(id)arg3 ;
-(BOOL)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3 ;
-(id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2 ;
-(long long)targetDisplayModeForActionInSplitViewController:(id)arg1 ;
-(WAPageCollectionViewController *)pageController;
-(void)setPageController:(WAPageCollectionViewController *)arg1 ;
-(void)setSplitViewController:(UISplitViewController *)arg1 ;
-(void)_reachabilityChanged:(id)arg1 ;
-(WACardCollectionViewController *)cardController;
-(void)setCardController:(WACardCollectionViewController *)arg1 ;
-(BOOL)viewDidAppear;
-(NSArray *)cities;
-(void)setCities:(NSArray *)arg1 ;
-(void)_stopUpdateTimer;
-(void)_startUpdateTimer;
-(void)setViewDidAppear:(BOOL)arg1 ;
-(void)setLocalWeatherEnabled:(BOOL)arg1 ;
-(id)initWithPreferences:(id)arg1 ;
-(void)cityDidUpdateWeather:(id)arg1 ;
-(void)city:(id)arg1 failedToUpdateWithError:(id)arg2 ;
-(void)setActiveCity:(City *)arg1 ;
-(void)addAndUpdateViewsForCity:(id)arg1 ;
-(void)showPageForCityAtIndex:(long long)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)saveStateToDisk;
-(void)loadCities;
-(void)setTransitionManager:(WACollectionViewTransitionManager *)arg1 ;
@end

