/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:26:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UIButton.h>

@class UILabel, UIImageView;

@interface WAUnitSelectionControl : UIButton {

	long long _selectedState;
	UILabel* _celsiusLabel;
	UILabel* _fahrenheitLabel;
	UIImageView* _dividerImageView;

}

@property (assign,nonatomic) long long selectedState;                       //@synthesize selectedState=_selectedState - In the implementation block
@property (nonatomic,readonly) UILabel * celsiusLabel;                      //@synthesize celsiusLabel=_celsiusLabel - In the implementation block
@property (nonatomic,readonly) UILabel * fahrenheitLabel;                   //@synthesize fahrenheitLabel=_fahrenheitLabel - In the implementation block
@property (nonatomic,readonly) UIImageView * dividerImageView;              //@synthesize dividerImageView=_dividerImageView - In the implementation block
-(id)generateDivider;
-(void)setSelectedState:(long long)arg1 ;
-(long long)selectedState;
-(UILabel *)celsiusLabel;
-(UILabel *)fahrenheitLabel;
-(UIImageView *)dividerImageView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

