/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:26:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UICollectionViewCell.h>
#import <libobjc.A.dylib/CityUpdateObserver.h>

@protocol WAWeatherCollectionViewCellDelegate, WAWeatherCollectionViewCellLayoutDelegate;
@class City, UIButton, WUIDynamicWeatherBackground, NSArray, WAWeatherCityView, NSString;

@interface WAWeatherCollectionViewCell : UICollectionViewCell <CityUpdateObserver> {

	double _buttonWidth;
	BOOL _showingDeleteUI;
	BOOL _needsUIUpdateAfterReuse;
	City* _city;
	long long _mode;
	double _transitionProgress;
	double _textTopMargin;
	UIButton* _deleteButton;
	id<WAWeatherCollectionViewCellDelegate> _delegate;
	id<WAWeatherCollectionViewCellLayoutDelegate> _layoutDelegate;
	WUIDynamicWeatherBackground* _background;
	NSArray* _extraViews;
	double _deleteSliderOffset;
	WAWeatherCityView* _cityView;

}

@property (nonatomic,retain) WUIDynamicWeatherBackground * background;                                         //@synthesize background=_background - In the implementation block
@property (assign,nonatomic) double deleteSliderOffset;                                                        //@synthesize deleteSliderOffset=_deleteSliderOffset - In the implementation block
@property (assign,nonatomic) BOOL needsUIUpdateAfterReuse;                                                     //@synthesize needsUIUpdateAfterReuse=_needsUIUpdateAfterReuse - In the implementation block
@property (nonatomic,readonly) WAWeatherCityView * cityView;                                                   //@synthesize cityView=_cityView - In the implementation block
@property (nonatomic,readonly) City * city;                                                                    //@synthesize city=_city - In the implementation block
@property (nonatomic,readonly) long long mode;                                                                 //@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) double transitionProgress;                                                        //@synthesize transitionProgress=_transitionProgress - In the implementation block
@property (assign,nonatomic) double textTopMargin;                                                             //@synthesize textTopMargin=_textTopMargin - In the implementation block
@property (getter=isShowingDeleteUI,nonatomic,readonly) BOOL showingDeleteUI;                                  //@synthesize showingDeleteUI=_showingDeleteUI - In the implementation block
@property (nonatomic,readonly) UIButton * deleteButton;                                                        //@synthesize deleteButton=_deleteButton - In the implementation block
@property (assign,nonatomic,__weak) id<WAWeatherCollectionViewCellDelegate> delegate;                          //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<WAWeatherCollectionViewCellLayoutDelegate> layoutDelegate;              //@synthesize layoutDelegate=_layoutDelegate - In the implementation block
@property (nonatomic,retain) NSArray * extraViews;                                                             //@synthesize extraViews=_extraViews - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(WAWeatherCityView *)cityView;
-(void)willTransitionToSize:(CGSize)arg1 layoutOptions:(id)arg2 ;
-(void)animateTransitionToSize:(CGSize)arg1 layoutOptions:(id)arg2 ;
-(void)setExtraViews:(NSArray *)arg1 ;
-(void)useBackgroundView:(id)arg1 ;
-(id)relinquishBackground;
-(void)setCity:(id)arg1 andMode:(long long)arg2 ;
-(void)_createCityView;
-(void)refreshForUnitsChange;
-(void)_createBackground;
-(void)_layoutForShowingDeleteUI:(BOOL)arg1 ;
-(void)_updateBackgroundCondition;
-(void)setTextTopMargin:(double)arg1 ;
-(double)deleteButtonOriginXForOffset:(double)arg1 ;
-(double)deleteButtonWidthForOffset:(double)arg1 ;
-(void)setParallaxOffset:(double)arg1 isTransitionOffset:(BOOL)arg2 ;
-(id)relinquishCityView;
-(void)useCityView:(id)arg1 ;
-(void)beginTracking;
-(void)swipeByOffset:(double)arg1 ;
-(void)showDeleteUI:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setContentOffset:(CGPoint)arg1 cityViewPanOffset:(double)arg2 ;
-(double)textTopMargin;
-(BOOL)isShowingDeleteUI;
-(NSArray *)extraViews;
-(double)deleteSliderOffset;
-(void)setDeleteSliderOffset:(double)arg1 ;
-(BOOL)needsUIUpdateAfterReuse;
-(void)setNeedsUIUpdateAfterReuse:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<WAWeatherCollectionViewCellDelegate>)arg1 ;
-(void)dealloc;
-(id<WAWeatherCollectionViewCellDelegate>)delegate;
-(void)prepareForReuse;
-(void)delete:(id)arg1 ;
-(long long)mode;
-(void)applyLayoutAttributes:(id)arg1 ;
-(WUIDynamicWeatherBackground *)background;
-(void)setBackground:(WUIDynamicWeatherBackground *)arg1 ;
-(void)setTransitionProgress:(double)arg1 ;
-(double)transitionProgress;
-(UIButton *)deleteButton;
-(void)setLayoutDelegate:(id<WAWeatherCollectionViewCellLayoutDelegate>)arg1 ;
-(id<WAWeatherCollectionViewCellLayoutDelegate>)layoutDelegate;
-(void)cityDidStartWeatherUpdate:(id)arg1 ;
-(void)cityDidFinishWeatherUpdate:(id)arg1 ;
-(City *)city;
-(void)didTransitionToSize:(CGSize)arg1 ;
@end

