/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:37:22 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/NanoPreferenceBundles/Customization/NTKCustomization.bundle/NTKCustomization
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NTKCCFaceDetailViewControllerDelegate <NSObject>
@required
-(void)libraryDetail:(id)arg1 didSelectFace:(id)arg2;
-(BOOL)libraryDetail:(id)arg1 canRemoveFace:(id)arg2;
-(void)libraryDetail:(id)arg1 didRemoveFace:(id)arg2;

@end

