/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 4:37:22 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/NanoPreferenceBundles/Customization/NTKCustomization.bundle/NTKCustomization
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BridgePreferences/BPSNTKCustomization.h>

@interface NTKCompanionCustomization : BPSNTKCustomization
+(void)initialize;
-(id)facesViewController;
-(id)galleryViewController;
-(id)libraryViewController;
@end

