/*
* This header is generated by classdump-dyld 1.0
* on Saturday, February 25, 2017 at 6:58:59 AM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /usr/sbin/BTServer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileCoreServices/LSApplicationWorkspaceObserver.h>

@protocol UninstallObserverProtocol;
@class NSObject;

@interface UninstallObserver : LSApplicationWorkspaceObserver {

	NSObject*<UninstallObserverProtocol> _delegate;

}

@property (assign,nonatomic) NSObject*<UninstallObserverProtocol> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)init;
-(void)setDelegate:(NSObject*<UninstallObserverProtocol>)arg1 ;
-(void)dealloc;
-(NSObject*<UninstallObserverProtocol>)delegate;
-(void)applicationsDidUninstall:(id)arg1 ;
@end

