/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:57:27 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class BLTSectionInfoList;

@interface BLTNotificationEnabledSettingsLogger : NSObject {

	double _lastLogTime;
	BLTSectionInfoList* _sectionInfoList;

}

@property (nonatomic,retain) BLTSectionInfoList * sectionInfoList;              //@synthesize sectionInfoList=_sectionInfoList - In the implementation block
+(id)sharedNotificationEnabledSettingsLogger:(id)arg1 ;
-(id)init;
-(void)_performActivity:(id)arg1 ;
-(void)setSectionInfoList:(BLTSectionInfoList *)arg1 ;
-(void)_log;
-(BLTSectionInfoList *)sectionInfoList;
-(void)_registerActivity;
@end

