/*
* This header is generated by classdump-dyld 1.0
* on Sunday, February 5, 2017 at 3:57:27 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/BulletinDistributorCompanion.framework/BulletinDistributorCompanion
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BLTSectionInfoObserverDelegate <NSObject>
@optional
-(void)sectionInfoObserver:(id)arg1 removedSectionWithSectionID:(id)arg2;

@required
-(void)sectionInfoObserver:(id)arg1 updatedSectionInfo:(id)arg2 withUniversalSectionID:(id)arg3 displayName:(id)arg4;

@end

