/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 7, 2017 at 4:50:01 PM Eastern Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/MobileSMS.app/MobileSMS
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIScrollView, UIView, NSLayoutConstraint;

@interface CKWhatsNewViewController : UIViewController {

	BOOL __didAdjustScrollPosition;
	UIScrollView* __scrollView;
	UIView* __topContentView;
	UIView* __bottomContentView;
	NSLayoutConstraint* __topConstraint;

}

@property (nonatomic,copy,readonly) UIScrollView * _scrollView;                                              //@synthesize _scrollView=__scrollView - In the implementation block
@property (nonatomic,copy,readonly) UIView * _topContentView;                                                //@synthesize _topContentView=__topContentView - In the implementation block
@property (nonatomic,copy,readonly) UIView * _bottomContentView;                                             //@synthesize _bottomContentView=__bottomContentView - In the implementation block
@property (nonatomic,copy,readonly) NSLayoutConstraint * _topConstraint;                                     //@synthesize _topConstraint=__topConstraint - In the implementation block
@property (assign,setter=_setDidAdjustScrollPosition:,nonatomic) BOOL _didAdjustScrollPosition;              //@synthesize _didAdjustScrollPosition=__didAdjustScrollPosition - In the implementation block
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(UIScrollView *)_scrollView;
-(void)dismissViewControllerAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)viewDidLoad;
-(UIView *)_topContentView;
-(void)_handleContinueButton:(id)arg1 ;
-(NSLayoutConstraint *)_topConstraint;
-(BOOL)_didAdjustScrollPosition;
-(UIView *)_bottomContentView;
-(void)_setDidAdjustScrollPosition:(BOOL)arg1 ;
@end

