/*
* This header is generated by classdump-dyld 1.0
* on Saturday, April 22, 2017 at 12:44:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /Applications/Passbook.app/Passbook
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIApplication.h>

@interface PBKApplication : UIApplication
-(void)setupRunScrollCardList;
-(void)testSelectCard;
-(void)testFlipCard;
-(BOOL)runTest:(id)arg1 options:(id)arg2 ;
-(void)gotoBaseTestState;
@end

