/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, February 14, 2017 at 5:17:47 PM Greenwich Mean Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /System/Library/PrivateFrameworks/PassKitUIFoundation.framework/PassKitUIFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _UIBasicAnimationFactory <NSObject>
@optional
-(id)_timingFunctionForAnimation;
-(id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;
-(BOOL)_shouldAnimateAdditivelyForView:(id)arg1 withKeyPath:(id)arg2;

@required
-(id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end

